// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/app.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppUpdateReq) Reset() {
	*x = AppUpdateReq{}
	mi := &file_ruto_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUpdateReq) ProtoMessage() {}

func (x *AppUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUpdateReq.ProtoReflect.Descriptor instead.
func (*AppUpdateReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppUpdateReq) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type AppGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGetReq) Reset() {
	*x = AppGetReq{}
	mi := &file_ruto_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGetReq) ProtoMessage() {}

func (x *AppGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGetReq.ProtoReflect.Descriptor instead.
func (*AppGetReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AppListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *ListParamsSt          `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppListReq) Reset() {
	*x = AppListReq{}
	mi := &file_ruto_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListReq) ProtoMessage() {}

func (x *AppListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListReq.ProtoReflect.Descriptor instead.
func (*AppListReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *AppListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type AppListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*structpb.Struct     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppListRep) Reset() {
	*x = AppListRep{}
	mi := &file_ruto_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListRep) ProtoMessage() {}

func (x *AppListRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListRep.ProtoReflect.Descriptor instead.
func (*AppListRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *AppListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *AppListRep) GetResults() []*structpb.Struct {
	if x != nil {
		return x.Results
	}
	return nil
}

type AppCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppCreateRep) Reset() {
	*x = AppCreateRep{}
	mi := &file_ruto_v1_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppCreateRep) ProtoMessage() {}

func (x *AppCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppCreateRep.ProtoReflect.Descriptor instead.
func (*AppCreateRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *AppCreateRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AppSwaggerEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSwaggerEndpoint) Reset() {
	*x = AppSwaggerEndpoint{}
	mi := &file_ruto_v1_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSwaggerEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSwaggerEndpoint) ProtoMessage() {}

func (x *AppSwaggerEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSwaggerEndpoint.ProtoReflect.Descriptor instead.
func (*AppSwaggerEndpoint) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{5}
}

func (x *AppSwaggerEndpoint) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AppSwaggerEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AppSwaggerEndpointsDiffRep struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Unregistered      []*AppSwaggerEndpoint  `protobuf:"bytes,1,rep,name=unregistered,proto3" json:"unregistered,omitempty"`
	RegisteredInvalid []*AppSwaggerEndpoint  `protobuf:"bytes,2,rep,name=registered_invalid,json=registeredInvalid,proto3" json:"registered_invalid,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppSwaggerEndpointsDiffRep) Reset() {
	*x = AppSwaggerEndpointsDiffRep{}
	mi := &file_ruto_v1_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSwaggerEndpointsDiffRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSwaggerEndpointsDiffRep) ProtoMessage() {}

func (x *AppSwaggerEndpointsDiffRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSwaggerEndpointsDiffRep.ProtoReflect.Descriptor instead.
func (*AppSwaggerEndpointsDiffRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{6}
}

func (x *AppSwaggerEndpointsDiffRep) GetUnregistered() []*AppSwaggerEndpoint {
	if x != nil {
		return x.Unregistered
	}
	return nil
}

func (x *AppSwaggerEndpointsDiffRep) GetRegisteredInvalid() []*AppSwaggerEndpoint {
	if x != nil {
		return x.RegisteredInvalid
	}
	return nil
}

type AppGrpcReflectionEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGrpcReflectionEndpoint) Reset() {
	*x = AppGrpcReflectionEndpoint{}
	mi := &file_ruto_v1_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGrpcReflectionEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGrpcReflectionEndpoint) ProtoMessage() {}

func (x *AppGrpcReflectionEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGrpcReflectionEndpoint.ProtoReflect.Descriptor instead.
func (*AppGrpcReflectionEndpoint) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{7}
}

func (x *AppGrpcReflectionEndpoint) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AppGrpcReflectionEndpoint) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AppGrpcReflectionEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type AppGrpcReflectionEndpointsRep struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       []*AppGrpcReflectionEndpoint `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGrpcReflectionEndpointsRep) Reset() {
	*x = AppGrpcReflectionEndpointsRep{}
	mi := &file_ruto_v1_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGrpcReflectionEndpointsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGrpcReflectionEndpointsRep) ProtoMessage() {}

func (x *AppGrpcReflectionEndpointsRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGrpcReflectionEndpointsRep.ProtoReflect.Descriptor instead.
func (*AppGrpcReflectionEndpointsRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{8}
}

func (x *AppGrpcReflectionEndpointsRep) GetResults() []*AppGrpcReflectionEndpoint {
	if x != nil {
		return x.Results
	}
	return nil
}

type AppGetSwaggerUrlByBackendUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendUrl    string                 `protobuf:"bytes,1,opt,name=backend_url,json=backendUrl,proto3" json:"backend_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGetSwaggerUrlByBackendUrlReq) Reset() {
	*x = AppGetSwaggerUrlByBackendUrlReq{}
	mi := &file_ruto_v1_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGetSwaggerUrlByBackendUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGetSwaggerUrlByBackendUrlReq) ProtoMessage() {}

func (x *AppGetSwaggerUrlByBackendUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGetSwaggerUrlByBackendUrlReq.ProtoReflect.Descriptor instead.
func (*AppGetSwaggerUrlByBackendUrlReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{9}
}

func (x *AppGetSwaggerUrlByBackendUrlReq) GetBackendUrl() string {
	if x != nil {
		return x.BackendUrl
	}
	return ""
}

type AppGetSwaggerUrlByBackendUrlRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwaggerUrl    string                 `protobuf:"bytes,1,opt,name=swagger_url,json=swaggerUrl,proto3" json:"swagger_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppGetSwaggerUrlByBackendUrlRep) Reset() {
	*x = AppGetSwaggerUrlByBackendUrlRep{}
	mi := &file_ruto_v1_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppGetSwaggerUrlByBackendUrlRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGetSwaggerUrlByBackendUrlRep) ProtoMessage() {}

func (x *AppGetSwaggerUrlByBackendUrlRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGetSwaggerUrlByBackendUrlRep.ProtoReflect.Descriptor instead.
func (*AppGetSwaggerUrlByBackendUrlRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_app_proto_rawDescGZIP(), []int{10}
}

func (x *AppGetSwaggerUrlByBackendUrlRep) GetSwaggerUrl() string {
	if x != nil {
		return x.SwaggerUrl
	}
	return ""
}

var File_ruto_v1_app_proto protoreflect.FileDescriptor

const file_ruto_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x11ruto_v1/app.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14ruto_v1/common.proto\"K\n" +
	"\fAppUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x1b\n" +
	"\tAppGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"l\n" +
	"\n" +
	"AppListReq\x126\n" +
	"\vlist_params\x18\x01 \x01(\v2\x15.ruto_v1.ListParamsStR\n" +
	"listParams\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01B\t\n" +
	"\a_active\"\x83\x01\n" +
	"\n" +
	"AppListRep\x12B\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x19.ruto_v1.PaginationInfoStR\x0epaginationInfo\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.google.protobuf.StructR\aresults\"\x1e\n" +
	"\fAppCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12AppSwaggerEndpoint\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xa9\x01\n" +
	"\x1aAppSwaggerEndpointsDiffRep\x12?\n" +
	"\funregistered\x18\x01 \x03(\v2\x1b.ruto_v1.AppSwaggerEndpointR\funregistered\x12J\n" +
	"\x12registered_invalid\x18\x02 \x03(\v2\x1b.ruto_v1.AppSwaggerEndpointR\x11registeredInvalid\"a\n" +
	"\x19AppGrpcReflectionEndpoint\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"]\n" +
	"\x1dAppGrpcReflectionEndpointsRep\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".ruto_v1.AppGrpcReflectionEndpointR\aresults\"B\n" +
	"\x1fAppGetSwaggerUrlByBackendUrlReq\x12\x1f\n" +
	"\vbackend_url\x18\x01 \x01(\tR\n" +
	"backendUrl\"B\n" +
	"\x1fAppGetSwaggerUrlByBackendUrlRep\x12\x1f\n" +
	"\vswagger_url\x18\x01 \x01(\tR\n" +
	"swaggerUrl2\x93\x06\n" +
	"\x03App\x12>\n" +
	"\x04List\x12\x13.ruto_v1.AppListReq\x1a\x13.ruto_v1.AppListRep\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/app\x12E\n" +
	"\x03Get\x12\x12.ruto_v1.AppGetReq\x1a\x17.google.protobuf.Struct\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/app/{id}\x12I\n" +
	"\x06Create\x12\x17.google.protobuf.Struct\x1a\x15.ruto_v1.AppCreateRep\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/app\x12P\n" +
	"\x06Update\x12\x15.ruto_v1.AppUpdateReq\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x04data\x1a\t/app/{id}\x12G\n" +
	"\x06Delete\x12\x12.ruto_v1.AppGetReq\x1a\x16.google.protobuf.Empty\"\x11\x82\xd3\xe4\x93\x02\v*\t/app/{id}\x12|\n" +
	"\x17GetSwaggerEndpointsDiff\x12\x12.ruto_v1.AppGetReq\x1a#.ruto_v1.AppSwaggerEndpointsDiffRep\"(\x82\xd3\xe4\x93\x02\"\x12 /app/{id}/swagger/endpoints-diff\x12\x85\x01\n" +
	"\x1aGetGrpcReflectionEndpoints\x12\x12.ruto_v1.AppGetReq\x1a&.ruto_v1.AppGrpcReflectionEndpointsRep\"+\x82\xd3\xe4\x93\x02%\x12#/app/{id}/grpc/reflection/endpoints\x12\x98\x01\n" +
	"\x19GetSwaggerUrlByBackendUrl\x12(.ruto_v1.AppGetSwaggerUrlByBackendUrlReq\x1a(.ruto_v1.AppGetSwaggerUrlByBackendUrlRep\"'\x82\xd3\xe4\x93\x02!\x12\x1f/app/swagger/url/by-backend-urlB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_app_proto_rawDescOnce sync.Once
	file_ruto_v1_app_proto_rawDescData []byte
)

func file_ruto_v1_app_proto_rawDescGZIP() []byte {
	file_ruto_v1_app_proto_rawDescOnce.Do(func() {
		file_ruto_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_app_proto_rawDesc), len(file_ruto_v1_app_proto_rawDesc)))
	})
	return file_ruto_v1_app_proto_rawDescData
}

var file_ruto_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ruto_v1_app_proto_goTypes = []any{
	(*AppUpdateReq)(nil),                    // 0: ruto_v1.AppUpdateReq
	(*AppGetReq)(nil),                       // 1: ruto_v1.AppGetReq
	(*AppListReq)(nil),                      // 2: ruto_v1.AppListReq
	(*AppListRep)(nil),                      // 3: ruto_v1.AppListRep
	(*AppCreateRep)(nil),                    // 4: ruto_v1.AppCreateRep
	(*AppSwaggerEndpoint)(nil),              // 5: ruto_v1.AppSwaggerEndpoint
	(*AppSwaggerEndpointsDiffRep)(nil),      // 6: ruto_v1.AppSwaggerEndpointsDiffRep
	(*AppGrpcReflectionEndpoint)(nil),       // 7: ruto_v1.AppGrpcReflectionEndpoint
	(*AppGrpcReflectionEndpointsRep)(nil),   // 8: ruto_v1.AppGrpcReflectionEndpointsRep
	(*AppGetSwaggerUrlByBackendUrlReq)(nil), // 9: ruto_v1.AppGetSwaggerUrlByBackendUrlReq
	(*AppGetSwaggerUrlByBackendUrlRep)(nil), // 10: ruto_v1.AppGetSwaggerUrlByBackendUrlRep
	(*structpb.Struct)(nil),                 // 11: google.protobuf.Struct
	(*ListParamsSt)(nil),                    // 12: ruto_v1.ListParamsSt
	(*PaginationInfoSt)(nil),                // 13: ruto_v1.PaginationInfoSt
	(*emptypb.Empty)(nil),                   // 14: google.protobuf.Empty
}
var file_ruto_v1_app_proto_depIdxs = []int32{
	11, // 0: ruto_v1.AppUpdateReq.data:type_name -> google.protobuf.Struct
	12, // 1: ruto_v1.AppListReq.list_params:type_name -> ruto_v1.ListParamsSt
	13, // 2: ruto_v1.AppListRep.pagination_info:type_name -> ruto_v1.PaginationInfoSt
	11, // 3: ruto_v1.AppListRep.results:type_name -> google.protobuf.Struct
	5,  // 4: ruto_v1.AppSwaggerEndpointsDiffRep.unregistered:type_name -> ruto_v1.AppSwaggerEndpoint
	5,  // 5: ruto_v1.AppSwaggerEndpointsDiffRep.registered_invalid:type_name -> ruto_v1.AppSwaggerEndpoint
	7,  // 6: ruto_v1.AppGrpcReflectionEndpointsRep.results:type_name -> ruto_v1.AppGrpcReflectionEndpoint
	2,  // 7: ruto_v1.App.List:input_type -> ruto_v1.AppListReq
	1,  // 8: ruto_v1.App.Get:input_type -> ruto_v1.AppGetReq
	11, // 9: ruto_v1.App.Create:input_type -> google.protobuf.Struct
	0,  // 10: ruto_v1.App.Update:input_type -> ruto_v1.AppUpdateReq
	1,  // 11: ruto_v1.App.Delete:input_type -> ruto_v1.AppGetReq
	1,  // 12: ruto_v1.App.GetSwaggerEndpointsDiff:input_type -> ruto_v1.AppGetReq
	1,  // 13: ruto_v1.App.GetGrpcReflectionEndpoints:input_type -> ruto_v1.AppGetReq
	9,  // 14: ruto_v1.App.GetSwaggerUrlByBackendUrl:input_type -> ruto_v1.AppGetSwaggerUrlByBackendUrlReq
	3,  // 15: ruto_v1.App.List:output_type -> ruto_v1.AppListRep
	11, // 16: ruto_v1.App.Get:output_type -> google.protobuf.Struct
	4,  // 17: ruto_v1.App.Create:output_type -> ruto_v1.AppCreateRep
	14, // 18: ruto_v1.App.Update:output_type -> google.protobuf.Empty
	14, // 19: ruto_v1.App.Delete:output_type -> google.protobuf.Empty
	6,  // 20: ruto_v1.App.GetSwaggerEndpointsDiff:output_type -> ruto_v1.AppSwaggerEndpointsDiffRep
	8,  // 21: ruto_v1.App.GetGrpcReflectionEndpoints:output_type -> ruto_v1.AppGrpcReflectionEndpointsRep
	10, // 22: ruto_v1.App.GetSwaggerUrlByBackendUrl:output_type -> ruto_v1.AppGetSwaggerUrlByBackendUrlRep
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ruto_v1_app_proto_init() }
func file_ruto_v1_app_proto_init() {
	if File_ruto_v1_app_proto != nil {
		return
	}
	file_ruto_v1_common_proto_init()
	file_ruto_v1_app_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_app_proto_rawDesc), len(file_ruto_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_app_proto_goTypes,
		DependencyIndexes: file_ruto_v1_app_proto_depIdxs,
		MessageInfos:      file_ruto_v1_app_proto_msgTypes,
	}.Build()
	File_ruto_v1_app_proto = out.File
	file_ruto_v1_app_proto_goTypes = nil
	file_ruto_v1_app_proto_depIdxs = nil
}
