// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: ruto_v1/app.proto

package ruto_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	App_List_FullMethodName                       = "/ruto_v1.App/List"
	App_Get_FullMethodName                        = "/ruto_v1.App/Get"
	App_Create_FullMethodName                     = "/ruto_v1.App/Create"
	App_Update_FullMethodName                     = "/ruto_v1.App/Update"
	App_Delete_FullMethodName                     = "/ruto_v1.App/Delete"
	App_GetSwaggerEndpointsDiff_FullMethodName    = "/ruto_v1.App/GetSwaggerEndpointsDiff"
	App_GetGrpcReflectionEndpoints_FullMethodName = "/ruto_v1.App/GetGrpcReflectionEndpoints"
	App_GetSwaggerUrlByBackendUrl_FullMethodName  = "/ruto_v1.App/GetSwaggerUrlByBackendUrl"
)

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppClient interface {
	List(ctx context.Context, in *AppListReq, opts ...grpc.CallOption) (*AppListRep, error)
	Get(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*AppMain, error)
	Create(ctx context.Context, in *AppMain, opts ...grpc.CallOption) (*AppCreateRep, error)
	Update(ctx context.Context, in *AppMain, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSwaggerEndpointsDiff(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*AppSwaggerEndpointsDiffRep, error)
	GetGrpcReflectionEndpoints(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*AppGrpcReflectionEndpointsRep, error)
	GetSwaggerUrlByBackendUrl(ctx context.Context, in *AppGetSwaggerUrlByBackendUrlReq, opts ...grpc.CallOption) (*AppGetSwaggerUrlByBackendUrlRep, error)
}

type appClient struct {
	cc grpc.ClientConnInterface
}

func NewAppClient(cc grpc.ClientConnInterface) AppClient {
	return &appClient{cc}
}

func (c *appClient) List(ctx context.Context, in *AppListReq, opts ...grpc.CallOption) (*AppListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppListRep)
	err := c.cc.Invoke(ctx, App_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Get(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*AppMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppMain)
	err := c.cc.Invoke(ctx, App_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Create(ctx context.Context, in *AppMain, opts ...grpc.CallOption) (*AppCreateRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppCreateRep)
	err := c.cc.Invoke(ctx, App_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Update(ctx context.Context, in *AppMain, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, App_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) Delete(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, App_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetSwaggerEndpointsDiff(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*AppSwaggerEndpointsDiffRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppSwaggerEndpointsDiffRep)
	err := c.cc.Invoke(ctx, App_GetSwaggerEndpointsDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetGrpcReflectionEndpoints(ctx context.Context, in *AppGetReq, opts ...grpc.CallOption) (*AppGrpcReflectionEndpointsRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppGrpcReflectionEndpointsRep)
	err := c.cc.Invoke(ctx, App_GetGrpcReflectionEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetSwaggerUrlByBackendUrl(ctx context.Context, in *AppGetSwaggerUrlByBackendUrlReq, opts ...grpc.CallOption) (*AppGetSwaggerUrlByBackendUrlRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppGetSwaggerUrlByBackendUrlRep)
	err := c.cc.Invoke(ctx, App_GetSwaggerUrlByBackendUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
// All implementations must embed UnimplementedAppServer
// for forward compatibility.
type AppServer interface {
	List(context.Context, *AppListReq) (*AppListRep, error)
	Get(context.Context, *AppGetReq) (*AppMain, error)
	Create(context.Context, *AppMain) (*AppCreateRep, error)
	Update(context.Context, *AppMain) (*emptypb.Empty, error)
	Delete(context.Context, *AppGetReq) (*emptypb.Empty, error)
	GetSwaggerEndpointsDiff(context.Context, *AppGetReq) (*AppSwaggerEndpointsDiffRep, error)
	GetGrpcReflectionEndpoints(context.Context, *AppGetReq) (*AppGrpcReflectionEndpointsRep, error)
	GetSwaggerUrlByBackendUrl(context.Context, *AppGetSwaggerUrlByBackendUrlReq) (*AppGetSwaggerUrlByBackendUrlRep, error)
	mustEmbedUnimplementedAppServer()
}

// UnimplementedAppServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppServer struct{}

func (UnimplementedAppServer) List(context.Context, *AppListReq) (*AppListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAppServer) Get(context.Context, *AppGetReq) (*AppMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAppServer) Create(context.Context, *AppMain) (*AppCreateRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAppServer) Update(context.Context, *AppMain) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAppServer) Delete(context.Context, *AppGetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAppServer) GetSwaggerEndpointsDiff(context.Context, *AppGetReq) (*AppSwaggerEndpointsDiffRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSwaggerEndpointsDiff not implemented")
}
func (UnimplementedAppServer) GetGrpcReflectionEndpoints(context.Context, *AppGetReq) (*AppGrpcReflectionEndpointsRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGrpcReflectionEndpoints not implemented")
}
func (UnimplementedAppServer) GetSwaggerUrlByBackendUrl(context.Context, *AppGetSwaggerUrlByBackendUrlReq) (*AppGetSwaggerUrlByBackendUrlRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSwaggerUrlByBackendUrl not implemented")
}
func (UnimplementedAppServer) mustEmbedUnimplementedAppServer() {}
func (UnimplementedAppServer) testEmbeddedByValue()             {}

// UnsafeAppServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppServer will
// result in compilation errors.
type UnsafeAppServer interface {
	mustEmbedUnimplementedAppServer()
}

func RegisterAppServer(s grpc.ServiceRegistrar, srv AppServer) {
	// If the following call pancis, it indicates UnimplementedAppServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&App_ServiceDesc, srv)
}

func _App_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).List(ctx, req.(*AppListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Get(ctx, req.(*AppGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppMain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Create(ctx, req.(*AppMain))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppMain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Update(ctx, req.(*AppMain))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).Delete(ctx, req.(*AppGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetSwaggerEndpointsDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetSwaggerEndpointsDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetSwaggerEndpointsDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetSwaggerEndpointsDiff(ctx, req.(*AppGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetGrpcReflectionEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetGrpcReflectionEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetGrpcReflectionEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetGrpcReflectionEndpoints(ctx, req.(*AppGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetSwaggerUrlByBackendUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetSwaggerUrlByBackendUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetSwaggerUrlByBackendUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: App_GetSwaggerUrlByBackendUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetSwaggerUrlByBackendUrl(ctx, req.(*AppGetSwaggerUrlByBackendUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

// App_ServiceDesc is the grpc.ServiceDesc for App service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var App_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ruto_v1.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _App_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _App_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _App_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _App_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _App_Delete_Handler,
		},
		{
			MethodName: "GetSwaggerEndpointsDiff",
			Handler:    _App_GetSwaggerEndpointsDiff_Handler,
		},
		{
			MethodName: "GetGrpcReflectionEndpoints",
			Handler:    _App_GetGrpcReflectionEndpoints_Handler,
		},
		{
			MethodName: "GetSwaggerUrlByBackendUrl",
			Handler:    _App_GetSwaggerUrlByBackendUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ruto_v1/app.proto",
}
