// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: ruto_v1/endpoint.proto

package ruto_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Endpoint_List_FullMethodName   = "/ruto_v1.Endpoint/List"
	Endpoint_Get_FullMethodName    = "/ruto_v1.Endpoint/Get"
	Endpoint_Create_FullMethodName = "/ruto_v1.Endpoint/Create"
	Endpoint_Update_FullMethodName = "/ruto_v1.Endpoint/Update"
	Endpoint_Delete_FullMethodName = "/ruto_v1.Endpoint/Delete"
)

// EndpointClient is the client API for Endpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointClient interface {
	List(ctx context.Context, in *EndpointListReq, opts ...grpc.CallOption) (*EndpointListRep, error)
	Get(ctx context.Context, in *EndpointGetReq, opts ...grpc.CallOption) (*EndpointMain, error)
	Create(ctx context.Context, in *EndpointMain, opts ...grpc.CallOption) (*EndpointCreateRep, error)
	Update(ctx context.Context, in *EndpointMain, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *EndpointGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type endpointClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointClient(cc grpc.ClientConnInterface) EndpointClient {
	return &endpointClient{cc}
}

func (c *endpointClient) List(ctx context.Context, in *EndpointListReq, opts ...grpc.CallOption) (*EndpointListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndpointListRep)
	err := c.cc.Invoke(ctx, Endpoint_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointClient) Get(ctx context.Context, in *EndpointGetReq, opts ...grpc.CallOption) (*EndpointMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndpointMain)
	err := c.cc.Invoke(ctx, Endpoint_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointClient) Create(ctx context.Context, in *EndpointMain, opts ...grpc.CallOption) (*EndpointCreateRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndpointCreateRep)
	err := c.cc.Invoke(ctx, Endpoint_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointClient) Update(ctx context.Context, in *EndpointMain, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Endpoint_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointClient) Delete(ctx context.Context, in *EndpointGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Endpoint_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointServer is the server API for Endpoint service.
// All implementations must embed UnimplementedEndpointServer
// for forward compatibility.
type EndpointServer interface {
	List(context.Context, *EndpointListReq) (*EndpointListRep, error)
	Get(context.Context, *EndpointGetReq) (*EndpointMain, error)
	Create(context.Context, *EndpointMain) (*EndpointCreateRep, error)
	Update(context.Context, *EndpointMain) (*emptypb.Empty, error)
	Delete(context.Context, *EndpointGetReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedEndpointServer()
}

// UnimplementedEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEndpointServer struct{}

func (UnimplementedEndpointServer) List(context.Context, *EndpointListReq) (*EndpointListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEndpointServer) Get(context.Context, *EndpointGetReq) (*EndpointMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEndpointServer) Create(context.Context, *EndpointMain) (*EndpointCreateRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEndpointServer) Update(context.Context, *EndpointMain) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEndpointServer) Delete(context.Context, *EndpointGetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEndpointServer) mustEmbedUnimplementedEndpointServer() {}
func (UnimplementedEndpointServer) testEmbeddedByValue()                  {}

// UnsafeEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointServer will
// result in compilation errors.
type UnsafeEndpointServer interface {
	mustEmbedUnimplementedEndpointServer()
}

func RegisterEndpointServer(s grpc.ServiceRegistrar, srv EndpointServer) {
	// If the following call pancis, it indicates UnimplementedEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Endpoint_ServiceDesc, srv)
}

func _Endpoint_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Endpoint_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServer).List(ctx, req.(*EndpointListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endpoint_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Endpoint_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServer).Get(ctx, req.(*EndpointGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endpoint_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointMain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Endpoint_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServer).Create(ctx, req.(*EndpointMain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endpoint_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointMain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Endpoint_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServer).Update(ctx, req.(*EndpointMain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endpoint_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Endpoint_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointServer).Delete(ctx, req.(*EndpointGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Endpoint_ServiceDesc is the grpc.ServiceDesc for Endpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Endpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ruto_v1.Endpoint",
	HandlerType: (*EndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Endpoint_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Endpoint_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Endpoint_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Endpoint_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Endpoint_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ruto_v1/endpoint.proto",
}
