// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/endpoint.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointUpdateReq) Reset() {
	*x = EndpointUpdateReq{}
	mi := &file_ruto_v1_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointUpdateReq) ProtoMessage() {}

func (x *EndpointUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointUpdateReq.ProtoReflect.Descriptor instead.
func (*EndpointUpdateReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndpointUpdateReq) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type EndpointGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointGetReq) Reset() {
	*x = EndpointGetReq{}
	mi := &file_ruto_v1_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointGetReq) ProtoMessage() {}

func (x *EndpointGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointGetReq.ProtoReflect.Descriptor instead.
func (*EndpointGetReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EndpointListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *ListParamsSt          `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	AppId         *string                `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3,oneof" json:"app_id,omitempty"`
	Active        *bool                  `protobuf:"varint,3,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointListReq) Reset() {
	*x = EndpointListReq{}
	mi := &file_ruto_v1_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointListReq) ProtoMessage() {}

func (x *EndpointListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointListReq.ProtoReflect.Descriptor instead.
func (*EndpointListReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *EndpointListReq) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *EndpointListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

type EndpointListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*structpb.Struct     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EndpointListRep) Reset() {
	*x = EndpointListRep{}
	mi := &file_ruto_v1_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointListRep) ProtoMessage() {}

func (x *EndpointListRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointListRep.ProtoReflect.Descriptor instead.
func (*EndpointListRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *EndpointListRep) GetResults() []*structpb.Struct {
	if x != nil {
		return x.Results
	}
	return nil
}

type EndpointCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointCreateRep) Reset() {
	*x = EndpointCreateRep{}
	mi := &file_ruto_v1_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointCreateRep) ProtoMessage() {}

func (x *EndpointCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointCreateRep.ProtoReflect.Descriptor instead.
func (*EndpointCreateRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *EndpointCreateRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EndpointVariablesEffectiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Variables     []*structpb.Struct     `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointVariablesEffectiveReq) Reset() {
	*x = EndpointVariablesEffectiveReq{}
	mi := &file_ruto_v1_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointVariablesEffectiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointVariablesEffectiveReq) ProtoMessage() {}

func (x *EndpointVariablesEffectiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointVariablesEffectiveReq.ProtoReflect.Descriptor instead.
func (*EndpointVariablesEffectiveReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *EndpointVariablesEffectiveReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndpointVariablesEffectiveReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *EndpointVariablesEffectiveReq) GetVariables() []*structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

var File_ruto_v1_endpoint_proto protoreflect.FileDescriptor

const file_ruto_v1_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x16ruto_v1/endpoint.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14ruto_v1/common.proto\"P\n" +
	"\x11EndpointUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\" \n" +
	"\x0eEndpointGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x01\n" +
	"\x0fEndpointListReq\x126\n" +
	"\vlist_params\x18\x01 \x01(\v2\x15.ruto_v1.ListParamsStR\n" +
	"listParams\x12\x1a\n" +
	"\x06app_id\x18\x02 \x01(\tH\x00R\x05appId\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x03 \x01(\bH\x01R\x06active\x88\x01\x01B\t\n" +
	"\a_app_idB\t\n" +
	"\a_active\"\x88\x01\n" +
	"\x0fEndpointListRep\x12B\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x19.ruto_v1.PaginationInfoStR\x0epaginationInfo\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.google.protobuf.StructR\aresults\"#\n" +
	"\x11EndpointCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\x1dEndpointVariablesEffectiveReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x125\n" +
	"\tvariables\x18\x03 \x03(\v2\x17.google.protobuf.StructR\tvariables2\xba\x04\n" +
	"\bEndpoint\x12M\n" +
	"\x04List\x12\x18.ruto_v1.EndpointListReq\x1a\x18.ruto_v1.EndpointListRep\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/endpoint\x12O\n" +
	"\x03Get\x12\x17.ruto_v1.EndpointGetReq\x1a\x17.google.protobuf.Struct\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/endpoint/{id}\x12S\n" +
	"\x06Create\x12\x17.google.protobuf.Struct\x1a\x1a.ruto_v1.EndpointCreateRep\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/endpoint\x12Z\n" +
	"\x06Update\x12\x1a.ruto_v1.EndpointUpdateReq\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x04data\x1a\x0e/endpoint/{id}\x12Q\n" +
	"\x06Delete\x12\x17.ruto_v1.EndpointGetReq\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/endpoint/{id}\x12\x89\x01\n" +
	"\x15GetVariablesEffective\x12&.ruto_v1.EndpointVariablesEffectiveReq\x1a\x1e.ruto_v1.VariablesEffectiveRep\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/endpoint/variables/effectiveB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_endpoint_proto_rawDescOnce sync.Once
	file_ruto_v1_endpoint_proto_rawDescData []byte
)

func file_ruto_v1_endpoint_proto_rawDescGZIP() []byte {
	file_ruto_v1_endpoint_proto_rawDescOnce.Do(func() {
		file_ruto_v1_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_endpoint_proto_rawDesc), len(file_ruto_v1_endpoint_proto_rawDesc)))
	})
	return file_ruto_v1_endpoint_proto_rawDescData
}

var file_ruto_v1_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ruto_v1_endpoint_proto_goTypes = []any{
	(*EndpointUpdateReq)(nil),             // 0: ruto_v1.EndpointUpdateReq
	(*EndpointGetReq)(nil),                // 1: ruto_v1.EndpointGetReq
	(*EndpointListReq)(nil),               // 2: ruto_v1.EndpointListReq
	(*EndpointListRep)(nil),               // 3: ruto_v1.EndpointListRep
	(*EndpointCreateRep)(nil),             // 4: ruto_v1.EndpointCreateRep
	(*EndpointVariablesEffectiveReq)(nil), // 5: ruto_v1.EndpointVariablesEffectiveReq
	(*structpb.Struct)(nil),               // 6: google.protobuf.Struct
	(*ListParamsSt)(nil),                  // 7: ruto_v1.ListParamsSt
	(*PaginationInfoSt)(nil),              // 8: ruto_v1.PaginationInfoSt
	(*emptypb.Empty)(nil),                 // 9: google.protobuf.Empty
	(*VariablesEffectiveRep)(nil),         // 10: ruto_v1.VariablesEffectiveRep
}
var file_ruto_v1_endpoint_proto_depIdxs = []int32{
	6,  // 0: ruto_v1.EndpointUpdateReq.data:type_name -> google.protobuf.Struct
	7,  // 1: ruto_v1.EndpointListReq.list_params:type_name -> ruto_v1.ListParamsSt
	8,  // 2: ruto_v1.EndpointListRep.pagination_info:type_name -> ruto_v1.PaginationInfoSt
	6,  // 3: ruto_v1.EndpointListRep.results:type_name -> google.protobuf.Struct
	6,  // 4: ruto_v1.EndpointVariablesEffectiveReq.variables:type_name -> google.protobuf.Struct
	2,  // 5: ruto_v1.Endpoint.List:input_type -> ruto_v1.EndpointListReq
	1,  // 6: ruto_v1.Endpoint.Get:input_type -> ruto_v1.EndpointGetReq
	6,  // 7: ruto_v1.Endpoint.Create:input_type -> google.protobuf.Struct
	0,  // 8: ruto_v1.Endpoint.Update:input_type -> ruto_v1.EndpointUpdateReq
	1,  // 9: ruto_v1.Endpoint.Delete:input_type -> ruto_v1.EndpointGetReq
	5,  // 10: ruto_v1.Endpoint.GetVariablesEffective:input_type -> ruto_v1.EndpointVariablesEffectiveReq
	3,  // 11: ruto_v1.Endpoint.List:output_type -> ruto_v1.EndpointListRep
	6,  // 12: ruto_v1.Endpoint.Get:output_type -> google.protobuf.Struct
	4,  // 13: ruto_v1.Endpoint.Create:output_type -> ruto_v1.EndpointCreateRep
	9,  // 14: ruto_v1.Endpoint.Update:output_type -> google.protobuf.Empty
	9,  // 15: ruto_v1.Endpoint.Delete:output_type -> google.protobuf.Empty
	10, // 16: ruto_v1.Endpoint.GetVariablesEffective:output_type -> ruto_v1.VariablesEffectiveRep
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ruto_v1_endpoint_proto_init() }
func file_ruto_v1_endpoint_proto_init() {
	if File_ruto_v1_endpoint_proto != nil {
		return
	}
	file_ruto_v1_common_proto_init()
	file_ruto_v1_endpoint_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_endpoint_proto_rawDesc), len(file_ruto_v1_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_endpoint_proto_goTypes,
		DependencyIndexes: file_ruto_v1_endpoint_proto_depIdxs,
		MessageInfos:      file_ruto_v1_endpoint_proto_msgTypes,
	}.Build()
	File_ruto_v1_endpoint_proto = out.File
	file_ruto_v1_endpoint_proto_goTypes = nil
	file_ruto_v1_endpoint_proto_depIdxs = nil
}
