// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/gateway.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewaySubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewaySubscribeRequest) Reset() {
	*x = GatewaySubscribeRequest{}
	mi := &file_ruto_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewaySubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewaySubscribeRequest) ProtoMessage() {}

func (x *GatewaySubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewaySubscribeRequest.ProtoReflect.Descriptor instead.
func (*GatewaySubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ruto_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewaySubscribeRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type GatewayNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type of notification, e.g. "check_version".
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayNotification) Reset() {
	*x = GatewayNotification{}
	mi := &file_ruto_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayNotification) ProtoMessage() {}

func (x *GatewayNotification) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayNotification.ProtoReflect.Descriptor instead.
func (*GatewayNotification) Descriptor() ([]byte, []int) {
	return file_ruto_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayNotification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GatewayHeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GatewayId        string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	HostName         string                 `protobuf:"bytes,5,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	SnapshotVersion  string                 `protobuf:"bytes,6,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	LastApplyAtUnix  int64                  `protobuf:"varint,7,opt,name=last_apply_at_unix,json=lastApplyAtUnix,proto3" json:"last_apply_at_unix,omitempty"`
	StartedAtUnix    int64                  `protobuf:"varint,8,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	LastError        string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	MemoryAllocBytes uint64                 `protobuf:"varint,10,opt,name=memory_alloc_bytes,json=memoryAllocBytes,proto3" json:"memory_alloc_bytes,omitempty"`
	GoroutinesCount  uint32                 `protobuf:"varint,11,opt,name=goroutines_count,json=goroutinesCount,proto3" json:"goroutines_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GatewayHeartbeatRequest) Reset() {
	*x = GatewayHeartbeatRequest{}
	mi := &file_ruto_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHeartbeatRequest) ProtoMessage() {}

func (x *GatewayHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*GatewayHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_ruto_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayHeartbeatRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayHeartbeatRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *GatewayHeartbeatRequest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *GatewayHeartbeatRequest) GetLastApplyAtUnix() int64 {
	if x != nil {
		return x.LastApplyAtUnix
	}
	return 0
}

func (x *GatewayHeartbeatRequest) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *GatewayHeartbeatRequest) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *GatewayHeartbeatRequest) GetMemoryAllocBytes() uint64 {
	if x != nil {
		return x.MemoryAllocBytes
	}
	return 0
}

func (x *GatewayHeartbeatRequest) GetGoroutinesCount() uint32 {
	if x != nil {
		return x.GoroutinesCount
	}
	return 0
}

type GatewayListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GatewayStateItem    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayListResponse) Reset() {
	*x = GatewayListResponse{}
	mi := &file_ruto_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayListResponse) ProtoMessage() {}

func (x *GatewayListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayListResponse.ProtoReflect.Descriptor instead.
func (*GatewayListResponse) Descriptor() ([]byte, []int) {
	return file_ruto_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayListResponse) GetResults() []*GatewayStateItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type GatewayStateItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GatewayId        string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	HostName         string                 `protobuf:"bytes,5,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	SnapshotVersion  string                 `protobuf:"bytes,6,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	LastApplyAtUnix  int64                  `protobuf:"varint,7,opt,name=last_apply_at_unix,json=lastApplyAtUnix,proto3" json:"last_apply_at_unix,omitempty"`
	StartedAtUnix    int64                  `protobuf:"varint,8,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	LastError        string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastSeenAtUnix   int64                  `protobuf:"varint,10,opt,name=last_seen_at_unix,json=lastSeenAtUnix,proto3" json:"last_seen_at_unix,omitempty"`
	Status           string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	MemoryAllocBytes uint64                 `protobuf:"varint,12,opt,name=memory_alloc_bytes,json=memoryAllocBytes,proto3" json:"memory_alloc_bytes,omitempty"`
	GoroutinesCount  uint32                 `protobuf:"varint,13,opt,name=goroutines_count,json=goroutinesCount,proto3" json:"goroutines_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GatewayStateItem) Reset() {
	*x = GatewayStateItem{}
	mi := &file_ruto_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStateItem) ProtoMessage() {}

func (x *GatewayStateItem) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStateItem.ProtoReflect.Descriptor instead.
func (*GatewayStateItem) Descriptor() ([]byte, []int) {
	return file_ruto_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayStateItem) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayStateItem) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *GatewayStateItem) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *GatewayStateItem) GetLastApplyAtUnix() int64 {
	if x != nil {
		return x.LastApplyAtUnix
	}
	return 0
}

func (x *GatewayStateItem) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *GatewayStateItem) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *GatewayStateItem) GetLastSeenAtUnix() int64 {
	if x != nil {
		return x.LastSeenAtUnix
	}
	return 0
}

func (x *GatewayStateItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GatewayStateItem) GetMemoryAllocBytes() uint64 {
	if x != nil {
		return x.MemoryAllocBytes
	}
	return 0
}

func (x *GatewayStateItem) GetGoroutinesCount() uint32 {
	if x != nil {
		return x.GoroutinesCount
	}
	return 0
}

var File_ruto_v1_gateway_proto protoreflect.FileDescriptor

const file_ruto_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15ruto_v1/gateway.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"8\n" +
	"\x17GatewaySubscribeRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\")\n" +
	"\x13GatewayNotification\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\xd3\x02\n" +
	"\x17GatewayHeartbeatRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1b\n" +
	"\thost_name\x18\x05 \x01(\tR\bhostName\x12)\n" +
	"\x10snapshot_version\x18\x06 \x01(\tR\x0fsnapshotVersion\x12+\n" +
	"\x12last_apply_at_unix\x18\a \x01(\x03R\x0flastApplyAtUnix\x12&\n" +
	"\x0fstarted_at_unix\x18\b \x01(\x03R\rstartedAtUnix\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12,\n" +
	"\x12memory_alloc_bytes\x18\n" +
	" \x01(\x04R\x10memoryAllocBytes\x12)\n" +
	"\x10goroutines_count\x18\v \x01(\rR\x0fgoroutinesCountJ\x04\b\x03\x10\x04\"J\n" +
	"\x13GatewayListResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.ruto_v1.GatewayStateItemR\aresults\"\x8f\x03\n" +
	"\x10GatewayStateItem\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1b\n" +
	"\thost_name\x18\x05 \x01(\tR\bhostName\x12)\n" +
	"\x10snapshot_version\x18\x06 \x01(\tR\x0fsnapshotVersion\x12+\n" +
	"\x12last_apply_at_unix\x18\a \x01(\x03R\x0flastApplyAtUnix\x12&\n" +
	"\x0fstarted_at_unix\x18\b \x01(\x03R\rstartedAtUnix\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12)\n" +
	"\x11last_seen_at_unix\x18\n" +
	" \x01(\x03R\x0elastSeenAtUnix\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12,\n" +
	"\x12memory_alloc_bytes\x18\f \x01(\x04R\x10memoryAllocBytes\x12)\n" +
	"\x10goroutines_count\x18\r \x01(\rR\x0fgoroutinesCountJ\x04\b\x03\x10\x042\xef\x01\n" +
	"\aGateway\x12E\n" +
	"\tHeartbeat\x12 .ruto_v1.GatewayHeartbeatRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x1c.ruto_v1.GatewayListResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/gateway\x12M\n" +
	"\tSubscribe\x12 .ruto_v1.GatewaySubscribeRequest\x1a\x1c.ruto_v1.GatewayNotification0\x01B\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_gateway_proto_rawDescOnce sync.Once
	file_ruto_v1_gateway_proto_rawDescData []byte
)

func file_ruto_v1_gateway_proto_rawDescGZIP() []byte {
	file_ruto_v1_gateway_proto_rawDescOnce.Do(func() {
		file_ruto_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_gateway_proto_rawDesc), len(file_ruto_v1_gateway_proto_rawDesc)))
	})
	return file_ruto_v1_gateway_proto_rawDescData
}

var file_ruto_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ruto_v1_gateway_proto_goTypes = []any{
	(*GatewaySubscribeRequest)(nil), // 0: ruto_v1.GatewaySubscribeRequest
	(*GatewayNotification)(nil),     // 1: ruto_v1.GatewayNotification
	(*GatewayHeartbeatRequest)(nil), // 2: ruto_v1.GatewayHeartbeatRequest
	(*GatewayListResponse)(nil),     // 3: ruto_v1.GatewayListResponse
	(*GatewayStateItem)(nil),        // 4: ruto_v1.GatewayStateItem
	(*emptypb.Empty)(nil),           // 5: google.protobuf.Empty
}
var file_ruto_v1_gateway_proto_depIdxs = []int32{
	4, // 0: ruto_v1.GatewayListResponse.results:type_name -> ruto_v1.GatewayStateItem
	2, // 1: ruto_v1.Gateway.Heartbeat:input_type -> ruto_v1.GatewayHeartbeatRequest
	5, // 2: ruto_v1.Gateway.List:input_type -> google.protobuf.Empty
	0, // 3: ruto_v1.Gateway.Subscribe:input_type -> ruto_v1.GatewaySubscribeRequest
	5, // 4: ruto_v1.Gateway.Heartbeat:output_type -> google.protobuf.Empty
	3, // 5: ruto_v1.Gateway.List:output_type -> ruto_v1.GatewayListResponse
	1, // 6: ruto_v1.Gateway.Subscribe:output_type -> ruto_v1.GatewayNotification
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ruto_v1_gateway_proto_init() }
func file_ruto_v1_gateway_proto_init() {
	if File_ruto_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_gateway_proto_rawDesc), len(file_ruto_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_gateway_proto_goTypes,
		DependencyIndexes: file_ruto_v1_gateway_proto_depIdxs,
		MessageInfos:      file_ruto_v1_gateway_proto_msgTypes,
	}.Build()
	File_ruto_v1_gateway_proto = out.File
	file_ruto_v1_gateway_proto_goTypes = nil
	file_ruto_v1_gateway_proto_depIdxs = nil
}
