// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/migrate.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MigrateRunReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmName     string                 `protobuf:"bytes,1,opt,name=realm_name,json=realmName,proto3" json:"realm_name,omitempty"`
	JwkUrl        string                 `protobuf:"bytes,2,opt,name=jwk_url,json=jwkUrl,proto3" json:"jwk_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRunReq) Reset() {
	*x = MigrateRunReq{}
	mi := &file_ruto_v1_migrate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRunReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRunReq) ProtoMessage() {}

func (x *MigrateRunReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_migrate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRunReq.ProtoReflect.Descriptor instead.
func (*MigrateRunReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_migrate_proto_rawDescGZIP(), []int{0}
}

func (x *MigrateRunReq) GetRealmName() string {
	if x != nil {
		return x.RealmName
	}
	return ""
}

func (x *MigrateRunReq) GetJwkUrl() string {
	if x != nil {
		return x.JwkUrl
	}
	return ""
}

type MigrateRunRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealmName     string                 `protobuf:"bytes,1,opt,name=realm_name,json=realmName,proto3" json:"realm_name,omitempty"`
	RootBaseUrl   string                 `protobuf:"bytes,2,opt,name=root_base_url,json=rootBaseUrl,proto3" json:"root_base_url,omitempty"`
	AppCount      int64                  `protobuf:"varint,3,opt,name=app_count,json=appCount,proto3" json:"app_count,omitempty"`
	EndpointCount int64                  `protobuf:"varint,4,opt,name=endpoint_count,json=endpointCount,proto3" json:"endpoint_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateRunRep) Reset() {
	*x = MigrateRunRep{}
	mi := &file_ruto_v1_migrate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateRunRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRunRep) ProtoMessage() {}

func (x *MigrateRunRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_migrate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRunRep.ProtoReflect.Descriptor instead.
func (*MigrateRunRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_migrate_proto_rawDescGZIP(), []int{1}
}

func (x *MigrateRunRep) GetRealmName() string {
	if x != nil {
		return x.RealmName
	}
	return ""
}

func (x *MigrateRunRep) GetRootBaseUrl() string {
	if x != nil {
		return x.RootBaseUrl
	}
	return ""
}

func (x *MigrateRunRep) GetAppCount() int64 {
	if x != nil {
		return x.AppCount
	}
	return 0
}

func (x *MigrateRunRep) GetEndpointCount() int64 {
	if x != nil {
		return x.EndpointCount
	}
	return 0
}

var File_ruto_v1_migrate_proto protoreflect.FileDescriptor

const file_ruto_v1_migrate_proto_rawDesc = "" +
	"\n" +
	"\x15ruto_v1/migrate.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\"G\n" +
	"\rMigrateRunReq\x12\x1d\n" +
	"\n" +
	"realm_name\x18\x01 \x01(\tR\trealmName\x12\x17\n" +
	"\ajwk_url\x18\x02 \x01(\tR\x06jwkUrl\"\x96\x01\n" +
	"\rMigrateRunRep\x12\x1d\n" +
	"\n" +
	"realm_name\x18\x01 \x01(\tR\trealmName\x12\"\n" +
	"\rroot_base_url\x18\x02 \x01(\tR\vrootBaseUrl\x12\x1b\n" +
	"\tapp_count\x18\x03 \x01(\x03R\bappCount\x12%\n" +
	"\x0eendpoint_count\x18\x04 \x01(\x03R\rendpointCount2Y\n" +
	"\aMigrate\x12N\n" +
	"\x03Run\x12\x16.ruto_v1.MigrateRunReq\x1a\x16.ruto_v1.MigrateRunRep\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/migrate/runB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_migrate_proto_rawDescOnce sync.Once
	file_ruto_v1_migrate_proto_rawDescData []byte
)

func file_ruto_v1_migrate_proto_rawDescGZIP() []byte {
	file_ruto_v1_migrate_proto_rawDescOnce.Do(func() {
		file_ruto_v1_migrate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_migrate_proto_rawDesc), len(file_ruto_v1_migrate_proto_rawDesc)))
	})
	return file_ruto_v1_migrate_proto_rawDescData
}

var file_ruto_v1_migrate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ruto_v1_migrate_proto_goTypes = []any{
	(*MigrateRunReq)(nil), // 0: ruto_v1.MigrateRunReq
	(*MigrateRunRep)(nil), // 1: ruto_v1.MigrateRunRep
}
var file_ruto_v1_migrate_proto_depIdxs = []int32{
	0, // 0: ruto_v1.Migrate.Run:input_type -> ruto_v1.MigrateRunReq
	1, // 1: ruto_v1.Migrate.Run:output_type -> ruto_v1.MigrateRunRep
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ruto_v1_migrate_proto_init() }
func file_ruto_v1_migrate_proto_init() {
	if File_ruto_v1_migrate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_migrate_proto_rawDesc), len(file_ruto_v1_migrate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_migrate_proto_goTypes,
		DependencyIndexes: file_ruto_v1_migrate_proto_depIdxs,
		MessageInfos:      file_ruto_v1_migrate_proto_msgTypes,
	}.Build()
	File_ruto_v1_migrate_proto = out.File
	file_ruto_v1_migrate_proto_goTypes = nil
	file_ruto_v1_migrate_proto_depIdxs = nil
}
