// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: ruto_v1/migrate.proto

package ruto_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migrate_Run_FullMethodName = "/ruto_v1.Migrate/Run"
)

// MigrateClient is the client API for Migrate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrateClient interface {
	Run(ctx context.Context, in *MigrateRunReq, opts ...grpc.CallOption) (*MigrateRunRep, error)
}

type migrateClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrateClient(cc grpc.ClientConnInterface) MigrateClient {
	return &migrateClient{cc}
}

func (c *migrateClient) Run(ctx context.Context, in *MigrateRunReq, opts ...grpc.CallOption) (*MigrateRunRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateRunRep)
	err := c.cc.Invoke(ctx, Migrate_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigrateServer is the server API for Migrate service.
// All implementations must embed UnimplementedMigrateServer
// for forward compatibility.
type MigrateServer interface {
	Run(context.Context, *MigrateRunReq) (*MigrateRunRep, error)
	mustEmbedUnimplementedMigrateServer()
}

// UnimplementedMigrateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigrateServer struct{}

func (UnimplementedMigrateServer) Run(context.Context, *MigrateRunReq) (*MigrateRunRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedMigrateServer) mustEmbedUnimplementedMigrateServer() {}
func (UnimplementedMigrateServer) testEmbeddedByValue()                 {}

// UnsafeMigrateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrateServer will
// result in compilation errors.
type UnsafeMigrateServer interface {
	mustEmbedUnimplementedMigrateServer()
}

func RegisterMigrateServer(s grpc.ServiceRegistrar, srv MigrateServer) {
	// If the following call pancis, it indicates UnimplementedMigrateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migrate_ServiceDesc, srv)
}

func _Migrate_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRunReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrateServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrate_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrateServer).Run(ctx, req.(*MigrateRunReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Migrate_ServiceDesc is the grpc.ServiceDesc for Migrate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migrate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ruto_v1.Migrate",
	HandlerType: (*MigrateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Migrate_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ruto_v1/migrate.proto",
}
