// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: ruto_v1/monitoring.proto

package ruto_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Monitoring_GetStatus_FullMethodName       = "/ruto_v1.Monitoring/GetStatus"
	Monitoring_AppMetrics_FullMethodName      = "/ruto_v1.Monitoring/AppMetrics"
	Monitoring_EndpointMetrics_FullMethodName = "/ruto_v1.Monitoring/EndpointMetrics"
	Monitoring_AppEndpointsRps_FullMethodName = "/ruto_v1.Monitoring/AppEndpointsRps"
	Monitoring_EndpointLogs_FullMethodName    = "/ruto_v1.Monitoring/EndpointLogs"
)

// MonitoringClient is the client API for Monitoring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitoringClient interface {
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MonitoringStatusResponse, error)
	AppMetrics(ctx context.Context, in *MonitoringMetricsRequest, opts ...grpc.CallOption) (*MonitoringSeriesResponse, error)
	EndpointMetrics(ctx context.Context, in *MonitoringMetricsRequest, opts ...grpc.CallOption) (*MonitoringSeriesResponse, error)
	AppEndpointsRps(ctx context.Context, in *MonitoringMetricsRequest, opts ...grpc.CallOption) (*MonitoringEndpointsRpsResponse, error)
	EndpointLogs(ctx context.Context, in *MonitoringLogsRequest, opts ...grpc.CallOption) (*MonitoringLogsResponse, error)
}

type monitoringClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringClient(cc grpc.ClientConnInterface) MonitoringClient {
	return &monitoringClient{cc}
}

func (c *monitoringClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MonitoringStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitoringStatusResponse)
	err := c.cc.Invoke(ctx, Monitoring_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringClient) AppMetrics(ctx context.Context, in *MonitoringMetricsRequest, opts ...grpc.CallOption) (*MonitoringSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitoringSeriesResponse)
	err := c.cc.Invoke(ctx, Monitoring_AppMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringClient) EndpointMetrics(ctx context.Context, in *MonitoringMetricsRequest, opts ...grpc.CallOption) (*MonitoringSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitoringSeriesResponse)
	err := c.cc.Invoke(ctx, Monitoring_EndpointMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringClient) AppEndpointsRps(ctx context.Context, in *MonitoringMetricsRequest, opts ...grpc.CallOption) (*MonitoringEndpointsRpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitoringEndpointsRpsResponse)
	err := c.cc.Invoke(ctx, Monitoring_AppEndpointsRps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitoringClient) EndpointLogs(ctx context.Context, in *MonitoringLogsRequest, opts ...grpc.CallOption) (*MonitoringLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitoringLogsResponse)
	err := c.cc.Invoke(ctx, Monitoring_EndpointLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitoringServer is the server API for Monitoring service.
// All implementations must embed UnimplementedMonitoringServer
// for forward compatibility.
type MonitoringServer interface {
	GetStatus(context.Context, *emptypb.Empty) (*MonitoringStatusResponse, error)
	AppMetrics(context.Context, *MonitoringMetricsRequest) (*MonitoringSeriesResponse, error)
	EndpointMetrics(context.Context, *MonitoringMetricsRequest) (*MonitoringSeriesResponse, error)
	AppEndpointsRps(context.Context, *MonitoringMetricsRequest) (*MonitoringEndpointsRpsResponse, error)
	EndpointLogs(context.Context, *MonitoringLogsRequest) (*MonitoringLogsResponse, error)
	mustEmbedUnimplementedMonitoringServer()
}

// UnimplementedMonitoringServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitoringServer struct{}

func (UnimplementedMonitoringServer) GetStatus(context.Context, *emptypb.Empty) (*MonitoringStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedMonitoringServer) AppMetrics(context.Context, *MonitoringMetricsRequest) (*MonitoringSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppMetrics not implemented")
}
func (UnimplementedMonitoringServer) EndpointMetrics(context.Context, *MonitoringMetricsRequest) (*MonitoringSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndpointMetrics not implemented")
}
func (UnimplementedMonitoringServer) AppEndpointsRps(context.Context, *MonitoringMetricsRequest) (*MonitoringEndpointsRpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppEndpointsRps not implemented")
}
func (UnimplementedMonitoringServer) EndpointLogs(context.Context, *MonitoringLogsRequest) (*MonitoringLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndpointLogs not implemented")
}
func (UnimplementedMonitoringServer) mustEmbedUnimplementedMonitoringServer() {}
func (UnimplementedMonitoringServer) testEmbeddedByValue()                    {}

// UnsafeMonitoringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServer will
// result in compilation errors.
type UnsafeMonitoringServer interface {
	mustEmbedUnimplementedMonitoringServer()
}

func RegisterMonitoringServer(s grpc.ServiceRegistrar, srv MonitoringServer) {
	// If the following call pancis, it indicates UnimplementedMonitoringServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Monitoring_ServiceDesc, srv)
}

func _Monitoring_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitoring_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitoring_AppMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoringMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServer).AppMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitoring_AppMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServer).AppMetrics(ctx, req.(*MonitoringMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitoring_EndpointMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoringMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServer).EndpointMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitoring_EndpointMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServer).EndpointMetrics(ctx, req.(*MonitoringMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitoring_AppEndpointsRps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoringMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServer).AppEndpointsRps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitoring_AppEndpointsRps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServer).AppEndpointsRps(ctx, req.(*MonitoringMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitoring_EndpointLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoringLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitoringServer).EndpointLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Monitoring_EndpointLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitoringServer).EndpointLogs(ctx, req.(*MonitoringLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Monitoring_ServiceDesc is the grpc.ServiceDesc for Monitoring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitoring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ruto_v1.Monitoring",
	HandlerType: (*MonitoringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Monitoring_GetStatus_Handler,
		},
		{
			MethodName: "AppMetrics",
			Handler:    _Monitoring_AppMetrics_Handler,
		},
		{
			MethodName: "EndpointMetrics",
			Handler:    _Monitoring_EndpointMetrics_Handler,
		},
		{
			MethodName: "AppEndpointsRps",
			Handler:    _Monitoring_AppEndpointsRps_Handler,
		},
		{
			MethodName: "EndpointLogs",
			Handler:    _Monitoring_EndpointLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ruto_v1/monitoring.proto",
}
