// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/monitoring.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonitoringStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MetricsEnabled bool                   `protobuf:"varint,1,opt,name=metrics_enabled,json=metricsEnabled,proto3" json:"metrics_enabled,omitempty"`
	LogsEnabled    bool                   `protobuf:"varint,2,opt,name=logs_enabled,json=logsEnabled,proto3" json:"logs_enabled,omitempty"`
	LogsProvider   string                 `protobuf:"bytes,3,opt,name=logs_provider,json=logsProvider,proto3" json:"logs_provider,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonitoringStatusResponse) Reset() {
	*x = MonitoringStatusResponse{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringStatusResponse) ProtoMessage() {}

func (x *MonitoringStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringStatusResponse.ProtoReflect.Descriptor instead.
func (*MonitoringStatusResponse) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *MonitoringStatusResponse) GetMetricsEnabled() bool {
	if x != nil {
		return x.MetricsEnabled
	}
	return false
}

func (x *MonitoringStatusResponse) GetLogsEnabled() bool {
	if x != nil {
		return x.LogsEnabled
	}
	return false
}

func (x *MonitoringStatusResponse) GetLogsProvider() string {
	if x != nil {
		return x.LogsProvider
	}
	return ""
}

type MonitoringMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RangeSeconds  int64                  `protobuf:"varint,2,opt,name=range_seconds,json=rangeSeconds,proto3" json:"range_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringMetricsRequest) Reset() {
	*x = MonitoringMetricsRequest{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringMetricsRequest) ProtoMessage() {}

func (x *MonitoringMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringMetricsRequest.ProtoReflect.Descriptor instead.
func (*MonitoringMetricsRequest) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *MonitoringMetricsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonitoringMetricsRequest) GetRangeSeconds() int64 {
	if x != nil {
		return x.RangeSeconds
	}
	return 0
}

type MonitoringSeriesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StepSeconds   int64                    `protobuf:"varint,1,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	Points        []*MonitoringSeriesPoint `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringSeriesResponse) Reset() {
	*x = MonitoringSeriesResponse{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringSeriesResponse) ProtoMessage() {}

func (x *MonitoringSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringSeriesResponse.ProtoReflect.Descriptor instead.
func (*MonitoringSeriesResponse) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *MonitoringSeriesResponse) GetStepSeconds() int64 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *MonitoringSeriesResponse) GetPoints() []*MonitoringSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type MonitoringSeriesPoint struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ts                 int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Rps                float64                `protobuf:"fixed64,2,opt,name=rps,proto3" json:"rps,omitempty"`
	DurationAvgSeconds float64                `protobuf:"fixed64,3,opt,name=duration_avg_seconds,json=durationAvgSeconds,proto3" json:"duration_avg_seconds,omitempty"`
	ErrorRate          float64                `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MonitoringSeriesPoint) Reset() {
	*x = MonitoringSeriesPoint{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringSeriesPoint) ProtoMessage() {}

func (x *MonitoringSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringSeriesPoint.ProtoReflect.Descriptor instead.
func (*MonitoringSeriesPoint) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *MonitoringSeriesPoint) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *MonitoringSeriesPoint) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *MonitoringSeriesPoint) GetDurationAvgSeconds() float64 {
	if x != nil {
		return x.DurationAvgSeconds
	}
	return 0
}

func (x *MonitoringSeriesPoint) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type MonitoringEndpointsRpsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StepSeconds   int64                    `protobuf:"varint,1,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	Results       []*MonitoringEndpointRps `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringEndpointsRpsResponse) Reset() {
	*x = MonitoringEndpointsRpsResponse{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringEndpointsRpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringEndpointsRpsResponse) ProtoMessage() {}

func (x *MonitoringEndpointsRpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringEndpointsRpsResponse.ProtoReflect.Descriptor instead.
func (*MonitoringEndpointsRpsResponse) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{4}
}

func (x *MonitoringEndpointsRpsResponse) GetStepSeconds() int64 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

func (x *MonitoringEndpointsRpsResponse) GetResults() []*MonitoringEndpointRps {
	if x != nil {
		return x.Results
	}
	return nil
}

type MonitoringEndpointRps struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	EndpointId    string                  `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Points        []*MonitoringValuePoint `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringEndpointRps) Reset() {
	*x = MonitoringEndpointRps{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringEndpointRps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringEndpointRps) ProtoMessage() {}

func (x *MonitoringEndpointRps) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringEndpointRps.ProtoReflect.Descriptor instead.
func (*MonitoringEndpointRps) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{5}
}

func (x *MonitoringEndpointRps) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *MonitoringEndpointRps) GetPoints() []*MonitoringValuePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type MonitoringValuePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringValuePoint) Reset() {
	*x = MonitoringValuePoint{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringValuePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringValuePoint) ProtoMessage() {}

func (x *MonitoringValuePoint) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringValuePoint.ProtoReflect.Descriptor instead.
func (*MonitoringValuePoint) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{6}
}

func (x *MonitoringValuePoint) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *MonitoringValuePoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MonitoringLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RangeSeconds  int64                  `protobuf:"varint,2,opt,name=range_seconds,json=rangeSeconds,proto3" json:"range_seconds,omitempty"`
	OnlyErrors    bool                   `protobuf:"varint,3,opt,name=only_errors,json=onlyErrors,proto3" json:"only_errors,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringLogsRequest) Reset() {
	*x = MonitoringLogsRequest{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringLogsRequest) ProtoMessage() {}

func (x *MonitoringLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringLogsRequest.ProtoReflect.Descriptor instead.
func (*MonitoringLogsRequest) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{7}
}

func (x *MonitoringLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MonitoringLogsRequest) GetRangeSeconds() int64 {
	if x != nil {
		return x.RangeSeconds
	}
	return 0
}

func (x *MonitoringLogsRequest) GetOnlyErrors() bool {
	if x != nil {
		return x.OnlyErrors
	}
	return false
}

func (x *MonitoringLogsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MonitoringLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MonitoringLogEntry  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringLogsResponse) Reset() {
	*x = MonitoringLogsResponse{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringLogsResponse) ProtoMessage() {}

func (x *MonitoringLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringLogsResponse.ProtoReflect.Descriptor instead.
func (*MonitoringLogsResponse) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{8}
}

func (x *MonitoringLogsResponse) GetResults() []*MonitoringLogEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type MonitoringLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Raw           string                 `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitoringLogEntry) Reset() {
	*x = MonitoringLogEntry{}
	mi := &file_ruto_v1_monitoring_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitoringLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitoringLogEntry) ProtoMessage() {}

func (x *MonitoringLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_monitoring_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitoringLogEntry.ProtoReflect.Descriptor instead.
func (*MonitoringLogEntry) Descriptor() ([]byte, []int) {
	return file_ruto_v1_monitoring_proto_rawDescGZIP(), []int{9}
}

func (x *MonitoringLogEntry) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *MonitoringLogEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MonitoringLogEntry) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *MonitoringLogEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MonitoringLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MonitoringLogEntry) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

var File_ruto_v1_monitoring_proto protoreflect.FileDescriptor

const file_ruto_v1_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x18ruto_v1/monitoring.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8b\x01\n" +
	"\x18MonitoringStatusResponse\x12'\n" +
	"\x0fmetrics_enabled\x18\x01 \x01(\bR\x0emetricsEnabled\x12!\n" +
	"\flogs_enabled\x18\x02 \x01(\bR\vlogsEnabled\x12#\n" +
	"\rlogs_provider\x18\x03 \x01(\tR\flogsProvider\"O\n" +
	"\x18MonitoringMetricsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrange_seconds\x18\x02 \x01(\x03R\frangeSeconds\"u\n" +
	"\x18MonitoringSeriesResponse\x12!\n" +
	"\fstep_seconds\x18\x01 \x01(\x03R\vstepSeconds\x126\n" +
	"\x06points\x18\x02 \x03(\v2\x1e.ruto_v1.MonitoringSeriesPointR\x06points\"\x8a\x01\n" +
	"\x15MonitoringSeriesPoint\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x10\n" +
	"\x03rps\x18\x02 \x01(\x01R\x03rps\x120\n" +
	"\x14duration_avg_seconds\x18\x03 \x01(\x01R\x12durationAvgSeconds\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\"}\n" +
	"\x1eMonitoringEndpointsRpsResponse\x12!\n" +
	"\fstep_seconds\x18\x01 \x01(\x03R\vstepSeconds\x128\n" +
	"\aresults\x18\x02 \x03(\v2\x1e.ruto_v1.MonitoringEndpointRpsR\aresults\"o\n" +
	"\x15MonitoringEndpointRps\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x125\n" +
	"\x06points\x18\x02 \x03(\v2\x1d.ruto_v1.MonitoringValuePointR\x06points\"<\n" +
	"\x14MonitoringValuePoint\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x83\x01\n" +
	"\x15MonitoringLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrange_seconds\x18\x02 \x01(\x03R\frangeSeconds\x12\x1f\n" +
	"\vonly_errors\x18\x03 \x01(\bR\n" +
	"onlyErrors\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"O\n" +
	"\x16MonitoringLogsResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.ruto_v1.MonitoringLogEntryR\aresults\"\x9f\x01\n" +
	"\x12MonitoringLogEntry\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x10\n" +
	"\x03raw\x18\x06 \x01(\tR\x03raw2\xf4\x04\n" +
	"\n" +
	"Monitoring\x12b\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a!.ruto_v1.MonitoringStatusResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/monitoring/status\x12x\n" +
	"\n" +
	"AppMetrics\x12!.ruto_v1.MonitoringMetricsRequest\x1a!.ruto_v1.MonitoringSeriesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/monitoring/app/{id}/metrics\x12\x82\x01\n" +
	"\x0fEndpointMetrics\x12!.ruto_v1.MonitoringMetricsRequest\x1a!.ruto_v1.MonitoringSeriesResponse\")\x82\xd3\xe4\x93\x02#\x12!/monitoring/endpoint/{id}/metrics\x12\x89\x01\n" +
	"\x0fAppEndpointsRps\x12!.ruto_v1.MonitoringMetricsRequest\x1a'.ruto_v1.MonitoringEndpointsRpsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/monitoring/app/{id}/endpoints-rps\x12w\n" +
	"\fEndpointLogs\x12\x1e.ruto_v1.MonitoringLogsRequest\x1a\x1f.ruto_v1.MonitoringLogsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/monitoring/endpoint/{id}/logsB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_monitoring_proto_rawDescOnce sync.Once
	file_ruto_v1_monitoring_proto_rawDescData []byte
)

func file_ruto_v1_monitoring_proto_rawDescGZIP() []byte {
	file_ruto_v1_monitoring_proto_rawDescOnce.Do(func() {
		file_ruto_v1_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_monitoring_proto_rawDesc), len(file_ruto_v1_monitoring_proto_rawDesc)))
	})
	return file_ruto_v1_monitoring_proto_rawDescData
}

var file_ruto_v1_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ruto_v1_monitoring_proto_goTypes = []any{
	(*MonitoringStatusResponse)(nil),       // 0: ruto_v1.MonitoringStatusResponse
	(*MonitoringMetricsRequest)(nil),       // 1: ruto_v1.MonitoringMetricsRequest
	(*MonitoringSeriesResponse)(nil),       // 2: ruto_v1.MonitoringSeriesResponse
	(*MonitoringSeriesPoint)(nil),          // 3: ruto_v1.MonitoringSeriesPoint
	(*MonitoringEndpointsRpsResponse)(nil), // 4: ruto_v1.MonitoringEndpointsRpsResponse
	(*MonitoringEndpointRps)(nil),          // 5: ruto_v1.MonitoringEndpointRps
	(*MonitoringValuePoint)(nil),           // 6: ruto_v1.MonitoringValuePoint
	(*MonitoringLogsRequest)(nil),          // 7: ruto_v1.MonitoringLogsRequest
	(*MonitoringLogsResponse)(nil),         // 8: ruto_v1.MonitoringLogsResponse
	(*MonitoringLogEntry)(nil),             // 9: ruto_v1.MonitoringLogEntry
	(*emptypb.Empty)(nil),                  // 10: google.protobuf.Empty
}
var file_ruto_v1_monitoring_proto_depIdxs = []int32{
	3,  // 0: ruto_v1.MonitoringSeriesResponse.points:type_name -> ruto_v1.MonitoringSeriesPoint
	5,  // 1: ruto_v1.MonitoringEndpointsRpsResponse.results:type_name -> ruto_v1.MonitoringEndpointRps
	6,  // 2: ruto_v1.MonitoringEndpointRps.points:type_name -> ruto_v1.MonitoringValuePoint
	9,  // 3: ruto_v1.MonitoringLogsResponse.results:type_name -> ruto_v1.MonitoringLogEntry
	10, // 4: ruto_v1.Monitoring.GetStatus:input_type -> google.protobuf.Empty
	1,  // 5: ruto_v1.Monitoring.AppMetrics:input_type -> ruto_v1.MonitoringMetricsRequest
	1,  // 6: ruto_v1.Monitoring.EndpointMetrics:input_type -> ruto_v1.MonitoringMetricsRequest
	1,  // 7: ruto_v1.Monitoring.AppEndpointsRps:input_type -> ruto_v1.MonitoringMetricsRequest
	7,  // 8: ruto_v1.Monitoring.EndpointLogs:input_type -> ruto_v1.MonitoringLogsRequest
	0,  // 9: ruto_v1.Monitoring.GetStatus:output_type -> ruto_v1.MonitoringStatusResponse
	2,  // 10: ruto_v1.Monitoring.AppMetrics:output_type -> ruto_v1.MonitoringSeriesResponse
	2,  // 11: ruto_v1.Monitoring.EndpointMetrics:output_type -> ruto_v1.MonitoringSeriesResponse
	4,  // 12: ruto_v1.Monitoring.AppEndpointsRps:output_type -> ruto_v1.MonitoringEndpointsRpsResponse
	8,  // 13: ruto_v1.Monitoring.EndpointLogs:output_type -> ruto_v1.MonitoringLogsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ruto_v1_monitoring_proto_init() }
func file_ruto_v1_monitoring_proto_init() {
	if File_ruto_v1_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_monitoring_proto_rawDesc), len(file_ruto_v1_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_monitoring_proto_goTypes,
		DependencyIndexes: file_ruto_v1_monitoring_proto_depIdxs,
		MessageInfos:      file_ruto_v1_monitoring_proto_msgTypes,
	}.Build()
	File_ruto_v1_monitoring_proto = out.File
	file_ruto_v1_monitoring_proto_goTypes = nil
	file_ruto_v1_monitoring_proto_depIdxs = nil
}
