// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/root.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RootMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicBaseUrl string                 `protobuf:"bytes,1,opt,name=public_base_url,json=publicBaseUrl,proto3" json:"public_base_url,omitempty"`
	Cors          *RootCors              `protobuf:"bytes,2,opt,name=cors,proto3" json:"cors,omitempty"`
	Jwt           []*RootJwt             `protobuf:"bytes,3,rep,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootMain) Reset() {
	*x = RootMain{}
	mi := &file_ruto_v1_root_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootMain) ProtoMessage() {}

func (x *RootMain) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_root_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootMain.ProtoReflect.Descriptor instead.
func (*RootMain) Descriptor() ([]byte, []int) {
	return file_ruto_v1_root_proto_rawDescGZIP(), []int{0}
}

func (x *RootMain) GetPublicBaseUrl() string {
	if x != nil {
		return x.PublicBaseUrl
	}
	return ""
}

func (x *RootMain) GetCors() *RootCors {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *RootMain) GetJwt() []*RootJwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type RootSetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicBaseUrl *string                `protobuf:"bytes,1,opt,name=public_base_url,json=publicBaseUrl,proto3,oneof" json:"public_base_url,omitempty"`
	Cors          *RootCors              `protobuf:"bytes,2,opt,name=cors,proto3,oneof" json:"cors,omitempty"`
	Jwt           []*RootJwt             `protobuf:"bytes,3,rep,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootSetReq) Reset() {
	*x = RootSetReq{}
	mi := &file_ruto_v1_root_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootSetReq) ProtoMessage() {}

func (x *RootSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_root_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootSetReq.ProtoReflect.Descriptor instead.
func (*RootSetReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_root_proto_rawDescGZIP(), []int{1}
}

func (x *RootSetReq) GetPublicBaseUrl() string {
	if x != nil && x.PublicBaseUrl != nil {
		return *x.PublicBaseUrl
	}
	return ""
}

func (x *RootSetReq) GetCors() *RootCors {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *RootSetReq) GetJwt() []*RootJwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type RootCors struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AllowCredentials bool                   `protobuf:"varint,2,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	MaxAge           string                 `protobuf:"bytes,3,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	AllowOrigins     []string               `protobuf:"bytes,4,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	AllowMethods     []string               `protobuf:"bytes,5,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	AllowHeaders     []string               `protobuf:"bytes,6,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RootCors) Reset() {
	*x = RootCors{}
	mi := &file_ruto_v1_root_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootCors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCors) ProtoMessage() {}

func (x *RootCors) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_root_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCors.ProtoReflect.Descriptor instead.
func (*RootCors) Descriptor() ([]byte, []int) {
	return file_ruto_v1_root_proto_rawDescGZIP(), []int{2}
}

func (x *RootCors) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RootCors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *RootCors) GetMaxAge() string {
	if x != nil {
		return x.MaxAge
	}
	return ""
}

func (x *RootCors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *RootCors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

func (x *RootCors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

type RootJwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwkUrl        string                 `protobuf:"bytes,1,opt,name=jwk_url,json=jwkUrl,proto3" json:"jwk_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootJwt) Reset() {
	*x = RootJwt{}
	mi := &file_ruto_v1_root_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootJwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootJwt) ProtoMessage() {}

func (x *RootJwt) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_root_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootJwt.ProtoReflect.Descriptor instead.
func (*RootJwt) Descriptor() ([]byte, []int) {
	return file_ruto_v1_root_proto_rawDescGZIP(), []int{3}
}

func (x *RootJwt) GetJwkUrl() string {
	if x != nil {
		return x.JwkUrl
	}
	return ""
}

var File_ruto_v1_root_proto protoreflect.FileDescriptor

const file_ruto_v1_root_proto_rawDesc = "" +
	"\n" +
	"\x12ruto_v1/root.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"}\n" +
	"\bRootMain\x12&\n" +
	"\x0fpublic_base_url\x18\x01 \x01(\tR\rpublicBaseUrl\x12%\n" +
	"\x04cors\x18\x02 \x01(\v2\x11.ruto_v1.RootCorsR\x04cors\x12\"\n" +
	"\x03jwt\x18\x03 \x03(\v2\x10.ruto_v1.RootJwtR\x03jwt\"\xa6\x01\n" +
	"\n" +
	"RootSetReq\x12+\n" +
	"\x0fpublic_base_url\x18\x01 \x01(\tH\x00R\rpublicBaseUrl\x88\x01\x01\x12*\n" +
	"\x04cors\x18\x02 \x01(\v2\x11.ruto_v1.RootCorsH\x01R\x04cors\x88\x01\x01\x12\"\n" +
	"\x03jwt\x18\x03 \x03(\v2\x10.ruto_v1.RootJwtR\x03jwtB\x12\n" +
	"\x10_public_base_urlB\a\n" +
	"\x05_cors\"\xd9\x01\n" +
	"\bRootCors\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12+\n" +
	"\x11allow_credentials\x18\x02 \x01(\bR\x10allowCredentials\x12\x17\n" +
	"\amax_age\x18\x03 \x01(\tR\x06maxAge\x12#\n" +
	"\rallow_origins\x18\x04 \x03(\tR\fallowOrigins\x12#\n" +
	"\rallow_methods\x18\x05 \x03(\tR\fallowMethods\x12#\n" +
	"\rallow_headers\x18\x06 \x03(\tR\fallowHeaders\"\"\n" +
	"\aRootJwt\x12\x17\n" +
	"\ajwk_url\x18\x01 \x01(\tR\x06jwkUrl2\x8d\x01\n" +
	"\x04Root\x12?\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x11.ruto_v1.RootMain\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/root\x12D\n" +
	"\x03Set\x12\x13.ruto_v1.RootSetReq\x1a\x16.google.protobuf.Empty\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/rootB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_root_proto_rawDescOnce sync.Once
	file_ruto_v1_root_proto_rawDescData []byte
)

func file_ruto_v1_root_proto_rawDescGZIP() []byte {
	file_ruto_v1_root_proto_rawDescOnce.Do(func() {
		file_ruto_v1_root_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_root_proto_rawDesc), len(file_ruto_v1_root_proto_rawDesc)))
	})
	return file_ruto_v1_root_proto_rawDescData
}

var file_ruto_v1_root_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ruto_v1_root_proto_goTypes = []any{
	(*RootMain)(nil),      // 0: ruto_v1.RootMain
	(*RootSetReq)(nil),    // 1: ruto_v1.RootSetReq
	(*RootCors)(nil),      // 2: ruto_v1.RootCors
	(*RootJwt)(nil),       // 3: ruto_v1.RootJwt
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_ruto_v1_root_proto_depIdxs = []int32{
	2, // 0: ruto_v1.RootMain.cors:type_name -> ruto_v1.RootCors
	3, // 1: ruto_v1.RootMain.jwt:type_name -> ruto_v1.RootJwt
	2, // 2: ruto_v1.RootSetReq.cors:type_name -> ruto_v1.RootCors
	3, // 3: ruto_v1.RootSetReq.jwt:type_name -> ruto_v1.RootJwt
	4, // 4: ruto_v1.Root.Get:input_type -> google.protobuf.Empty
	1, // 5: ruto_v1.Root.Set:input_type -> ruto_v1.RootSetReq
	0, // 6: ruto_v1.Root.Get:output_type -> ruto_v1.RootMain
	4, // 7: ruto_v1.Root.Set:output_type -> google.protobuf.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ruto_v1_root_proto_init() }
func file_ruto_v1_root_proto_init() {
	if File_ruto_v1_root_proto != nil {
		return
	}
	file_ruto_v1_root_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_root_proto_rawDesc), len(file_ruto_v1_root_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_root_proto_goTypes,
		DependencyIndexes: file_ruto_v1_root_proto_depIdxs,
		MessageInfos:      file_ruto_v1_root_proto_msgTypes,
	}.Build()
	File_ruto_v1_root_proto = out.File
	file_ruto_v1_root_proto_goTypes = nil
	file_ruto_v1_root_proto_depIdxs = nil
}
