// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/seen_path.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeenPathListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeenPathListReq) Reset() {
	*x = SeenPathListReq{}
	mi := &file_ruto_v1_seen_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeenPathListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeenPathListReq) ProtoMessage() {}

func (x *SeenPathListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_seen_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeenPathListReq.ProtoReflect.Descriptor instead.
func (*SeenPathListReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_seen_path_proto_rawDescGZIP(), []int{0}
}

func (x *SeenPathListReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type SeenPathListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SeenPathMain        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeenPathListRep) Reset() {
	*x = SeenPathListRep{}
	mi := &file_ruto_v1_seen_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeenPathListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeenPathListRep) ProtoMessage() {}

func (x *SeenPathListRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_seen_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeenPathListRep.ProtoReflect.Descriptor instead.
func (*SeenPathListRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_seen_path_proto_rawDescGZIP(), []int{1}
}

func (x *SeenPathListRep) GetResults() []*SeenPathMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type SeenPathClearReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeenPathClearReq) Reset() {
	*x = SeenPathClearReq{}
	mi := &file_ruto_v1_seen_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeenPathClearReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeenPathClearReq) ProtoMessage() {}

func (x *SeenPathClearReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_seen_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeenPathClearReq.ProtoReflect.Descriptor instead.
func (*SeenPathClearReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_seen_path_proto_rawDescGZIP(), []int{2}
}

func (x *SeenPathClearReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type SeenPathMain struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppId           string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	EndpointId      string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Method          string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Hits            int64                  `protobuf:"varint,5,opt,name=hits,proto3" json:"hits,omitempty"`
	HitsNotFound    int64                  `protobuf:"varint,6,opt,name=hits_not_found,json=hitsNotFound,proto3" json:"hits_not_found,omitempty"`
	FirstSeenAtUnix int64                  `protobuf:"varint,7,opt,name=first_seen_at_unix,json=firstSeenAtUnix,proto3" json:"first_seen_at_unix,omitempty"`
	LastSeenAtUnix  int64                  `protobuf:"varint,8,opt,name=last_seen_at_unix,json=lastSeenAtUnix,proto3" json:"last_seen_at_unix,omitempty"`
	Sample          string                 `protobuf:"bytes,9,opt,name=sample,proto3" json:"sample,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SeenPathMain) Reset() {
	*x = SeenPathMain{}
	mi := &file_ruto_v1_seen_path_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeenPathMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeenPathMain) ProtoMessage() {}

func (x *SeenPathMain) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_seen_path_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeenPathMain.ProtoReflect.Descriptor instead.
func (*SeenPathMain) Descriptor() ([]byte, []int) {
	return file_ruto_v1_seen_path_proto_rawDescGZIP(), []int{3}
}

func (x *SeenPathMain) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SeenPathMain) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *SeenPathMain) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SeenPathMain) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SeenPathMain) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *SeenPathMain) GetHitsNotFound() int64 {
	if x != nil {
		return x.HitsNotFound
	}
	return 0
}

func (x *SeenPathMain) GetFirstSeenAtUnix() int64 {
	if x != nil {
		return x.FirstSeenAtUnix
	}
	return 0
}

func (x *SeenPathMain) GetLastSeenAtUnix() int64 {
	if x != nil {
		return x.LastSeenAtUnix
	}
	return 0
}

func (x *SeenPathMain) GetSample() string {
	if x != nil {
		return x.Sample
	}
	return ""
}

var File_ruto_v1_seen_path_proto protoreflect.FileDescriptor

const file_ruto_v1_seen_path_proto_rawDesc = "" +
	"\n" +
	"\x17ruto_v1/seen_path.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"(\n" +
	"\x0fSeenPathListReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"B\n" +
	"\x0fSeenPathListRep\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.ruto_v1.SeenPathMainR\aresults\")\n" +
	"\x10SeenPathClearReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x9c\x02\n" +
	"\fSeenPathMain\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x12\n" +
	"\x04hits\x18\x05 \x01(\x03R\x04hits\x12$\n" +
	"\x0ehits_not_found\x18\x06 \x01(\x03R\fhitsNotFound\x12+\n" +
	"\x12first_seen_at_unix\x18\a \x01(\x03R\x0ffirstSeenAtUnix\x12)\n" +
	"\x11last_seen_at_unix\x18\b \x01(\x03R\x0elastSeenAtUnix\x12\x16\n" +
	"\x06sample\x18\t \x01(\tR\x06sample2\xaa\x01\n" +
	"\bSeenPath\x12N\n" +
	"\x04List\x12\x18.ruto_v1.SeenPathListReq\x1a\x18.ruto_v1.SeenPathListRep\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/seen_path\x12N\n" +
	"\x05Clear\x12\x19.ruto_v1.SeenPathClearReq\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/seen_pathB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_seen_path_proto_rawDescOnce sync.Once
	file_ruto_v1_seen_path_proto_rawDescData []byte
)

func file_ruto_v1_seen_path_proto_rawDescGZIP() []byte {
	file_ruto_v1_seen_path_proto_rawDescOnce.Do(func() {
		file_ruto_v1_seen_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_seen_path_proto_rawDesc), len(file_ruto_v1_seen_path_proto_rawDesc)))
	})
	return file_ruto_v1_seen_path_proto_rawDescData
}

var file_ruto_v1_seen_path_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ruto_v1_seen_path_proto_goTypes = []any{
	(*SeenPathListReq)(nil),  // 0: ruto_v1.SeenPathListReq
	(*SeenPathListRep)(nil),  // 1: ruto_v1.SeenPathListRep
	(*SeenPathClearReq)(nil), // 2: ruto_v1.SeenPathClearReq
	(*SeenPathMain)(nil),     // 3: ruto_v1.SeenPathMain
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_ruto_v1_seen_path_proto_depIdxs = []int32{
	3, // 0: ruto_v1.SeenPathListRep.results:type_name -> ruto_v1.SeenPathMain
	0, // 1: ruto_v1.SeenPath.List:input_type -> ruto_v1.SeenPathListReq
	2, // 2: ruto_v1.SeenPath.Clear:input_type -> ruto_v1.SeenPathClearReq
	1, // 3: ruto_v1.SeenPath.List:output_type -> ruto_v1.SeenPathListRep
	4, // 4: ruto_v1.SeenPath.Clear:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ruto_v1_seen_path_proto_init() }
func file_ruto_v1_seen_path_proto_init() {
	if File_ruto_v1_seen_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_seen_path_proto_rawDesc), len(file_ruto_v1_seen_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_seen_path_proto_goTypes,
		DependencyIndexes: file_ruto_v1_seen_path_proto_depIdxs,
		MessageInfos:      file_ruto_v1_seen_path_proto_msgTypes,
	}.Build()
	File_ruto_v1_seen_path_proto = out.File
	file_ruto_v1_seen_path_proto_goTypes = nil
	file_ruto_v1_seen_path_proto_depIdxs = nil
}
