// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: ruto_v1/seen_path.proto

package ruto_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeenPath_List_FullMethodName  = "/ruto_v1.SeenPath/List"
	SeenPath_Clear_FullMethodName = "/ruto_v1.SeenPath/Clear"
)

// SeenPathClient is the client API for SeenPath service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SeenPath reports which concrete paths were served by wildcard endpoints.
type SeenPathClient interface {
	List(ctx context.Context, in *SeenPathListReq, opts ...grpc.CallOption) (*SeenPathListRep, error)
	Clear(ctx context.Context, in *SeenPathClearReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type seenPathClient struct {
	cc grpc.ClientConnInterface
}

func NewSeenPathClient(cc grpc.ClientConnInterface) SeenPathClient {
	return &seenPathClient{cc}
}

func (c *seenPathClient) List(ctx context.Context, in *SeenPathListReq, opts ...grpc.CallOption) (*SeenPathListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeenPathListRep)
	err := c.cc.Invoke(ctx, SeenPath_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seenPathClient) Clear(ctx context.Context, in *SeenPathClearReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SeenPath_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeenPathServer is the server API for SeenPath service.
// All implementations must embed UnimplementedSeenPathServer
// for forward compatibility.
//
// SeenPath reports which concrete paths were served by wildcard endpoints.
type SeenPathServer interface {
	List(context.Context, *SeenPathListReq) (*SeenPathListRep, error)
	Clear(context.Context, *SeenPathClearReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedSeenPathServer()
}

// UnimplementedSeenPathServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeenPathServer struct{}

func (UnimplementedSeenPathServer) List(context.Context, *SeenPathListReq) (*SeenPathListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSeenPathServer) Clear(context.Context, *SeenPathClearReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedSeenPathServer) mustEmbedUnimplementedSeenPathServer() {}
func (UnimplementedSeenPathServer) testEmbeddedByValue()                  {}

// UnsafeSeenPathServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeenPathServer will
// result in compilation errors.
type UnsafeSeenPathServer interface {
	mustEmbedUnimplementedSeenPathServer()
}

func RegisterSeenPathServer(s grpc.ServiceRegistrar, srv SeenPathServer) {
	// If the following call pancis, it indicates UnimplementedSeenPathServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeenPath_ServiceDesc, srv)
}

func _SeenPath_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeenPathListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeenPathServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeenPath_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeenPathServer).List(ctx, req.(*SeenPathListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeenPath_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeenPathClearReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeenPathServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeenPath_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeenPathServer).Clear(ctx, req.(*SeenPathClearReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SeenPath_ServiceDesc is the grpc.ServiceDesc for SeenPath service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeenPath_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ruto_v1.SeenPath",
	HandlerType: (*SeenPathServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SeenPath_List_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _SeenPath_Clear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ruto_v1/seen_path.proto",
}
