// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/snapshot.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ruto_v1_snapshot_proto protoreflect.FileDescriptor

const file_ruto_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x16ruto_v1/snapshot.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto2U\n" +
	"\bSnapshot\x12I\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x17.google.protobuf.Struct\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/snapshotB\n" +
	"Z\b/ruto_v1b\x06proto3"

var file_ruto_v1_snapshot_proto_goTypes = []any{
	(*emptypb.Empty)(nil),   // 0: google.protobuf.Empty
	(*structpb.Struct)(nil), // 1: google.protobuf.Struct
}
var file_ruto_v1_snapshot_proto_depIdxs = []int32{
	0, // 0: ruto_v1.Snapshot.Get:input_type -> google.protobuf.Empty
	1, // 1: ruto_v1.Snapshot.Get:output_type -> google.protobuf.Struct
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ruto_v1_snapshot_proto_init() }
func file_ruto_v1_snapshot_proto_init() {
	if File_ruto_v1_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_snapshot_proto_rawDesc), len(file_ruto_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_ruto_v1_snapshot_proto_depIdxs,
	}.Build()
	File_ruto_v1_snapshot_proto = out.File
	file_ruto_v1_snapshot_proto_goTypes = nil
	file_ruto_v1_snapshot_proto_depIdxs = nil
}
