// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/stats.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AppsTotal         int64                  `protobuf:"varint,1,opt,name=apps_total,json=appsTotal,proto3" json:"apps_total,omitempty"`
	AppsActive        int64                  `protobuf:"varint,2,opt,name=apps_active,json=appsActive,proto3" json:"apps_active,omitempty"`
	AppsInactive      int64                  `protobuf:"varint,3,opt,name=apps_inactive,json=appsInactive,proto3" json:"apps_inactive,omitempty"`
	EndpointsTotal    int64                  `protobuf:"varint,4,opt,name=endpoints_total,json=endpointsTotal,proto3" json:"endpoints_total,omitempty"`
	EndpointsActive   int64                  `protobuf:"varint,5,opt,name=endpoints_active,json=endpointsActive,proto3" json:"endpoints_active,omitempty"`
	EndpointsInactive int64                  `protobuf:"varint,6,opt,name=endpoints_inactive,json=endpointsInactive,proto3" json:"endpoints_inactive,omitempty"`
	UsersTotal        int64                  `protobuf:"varint,7,opt,name=users_total,json=usersTotal,proto3" json:"users_total,omitempty"`
	UsersActive       int64                  `protobuf:"varint,8,opt,name=users_active,json=usersActive,proto3" json:"users_active,omitempty"`
	UsersAdmin        int64                  `protobuf:"varint,9,opt,name=users_admin,json=usersAdmin,proto3" json:"users_admin,omitempty"`
	RootJwtProviders  int64                  `protobuf:"varint,10,opt,name=root_jwt_providers,json=rootJwtProviders,proto3" json:"root_jwt_providers,omitempty"`
	RootAuthEnabled   bool                   `protobuf:"varint,11,opt,name=root_auth_enabled,json=rootAuthEnabled,proto3" json:"root_auth_enabled,omitempty"`
	RootCorsEnabled   bool                   `protobuf:"varint,12,opt,name=root_cors_enabled,json=rootCorsEnabled,proto3" json:"root_cors_enabled,omitempty"`
	Methods           []*StatsMethodStats    `protobuf:"bytes,13,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_ruto_v1_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_ruto_v1_stats_proto_rawDescGZIP(), []int{0}
}

func (x *StatsResponse) GetAppsTotal() int64 {
	if x != nil {
		return x.AppsTotal
	}
	return 0
}

func (x *StatsResponse) GetAppsActive() int64 {
	if x != nil {
		return x.AppsActive
	}
	return 0
}

func (x *StatsResponse) GetAppsInactive() int64 {
	if x != nil {
		return x.AppsInactive
	}
	return 0
}

func (x *StatsResponse) GetEndpointsTotal() int64 {
	if x != nil {
		return x.EndpointsTotal
	}
	return 0
}

func (x *StatsResponse) GetEndpointsActive() int64 {
	if x != nil {
		return x.EndpointsActive
	}
	return 0
}

func (x *StatsResponse) GetEndpointsInactive() int64 {
	if x != nil {
		return x.EndpointsInactive
	}
	return 0
}

func (x *StatsResponse) GetUsersTotal() int64 {
	if x != nil {
		return x.UsersTotal
	}
	return 0
}

func (x *StatsResponse) GetUsersActive() int64 {
	if x != nil {
		return x.UsersActive
	}
	return 0
}

func (x *StatsResponse) GetUsersAdmin() int64 {
	if x != nil {
		return x.UsersAdmin
	}
	return 0
}

func (x *StatsResponse) GetRootJwtProviders() int64 {
	if x != nil {
		return x.RootJwtProviders
	}
	return 0
}

func (x *StatsResponse) GetRootAuthEnabled() bool {
	if x != nil {
		return x.RootAuthEnabled
	}
	return false
}

func (x *StatsResponse) GetRootCorsEnabled() bool {
	if x != nil {
		return x.RootCorsEnabled
	}
	return false
}

func (x *StatsResponse) GetMethods() []*StatsMethodStats {
	if x != nil {
		return x.Methods
	}
	return nil
}

type StatsMethodStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Active        int64                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsMethodStats) Reset() {
	*x = StatsMethodStats{}
	mi := &file_ruto_v1_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsMethodStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsMethodStats) ProtoMessage() {}

func (x *StatsMethodStats) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsMethodStats.ProtoReflect.Descriptor instead.
func (*StatsMethodStats) Descriptor() ([]byte, []int) {
	return file_ruto_v1_stats_proto_rawDescGZIP(), []int{1}
}

func (x *StatsMethodStats) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *StatsMethodStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StatsMethodStats) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

var File_ruto_v1_stats_proto protoreflect.FileDescriptor

const file_ruto_v1_stats_proto_rawDesc = "" +
	"\n" +
	"\x13ruto_v1/stats.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x04\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"apps_total\x18\x01 \x01(\x03R\tappsTotal\x12\x1f\n" +
	"\vapps_active\x18\x02 \x01(\x03R\n" +
	"appsActive\x12#\n" +
	"\rapps_inactive\x18\x03 \x01(\x03R\fappsInactive\x12'\n" +
	"\x0fendpoints_total\x18\x04 \x01(\x03R\x0eendpointsTotal\x12)\n" +
	"\x10endpoints_active\x18\x05 \x01(\x03R\x0fendpointsActive\x12-\n" +
	"\x12endpoints_inactive\x18\x06 \x01(\x03R\x11endpointsInactive\x12\x1f\n" +
	"\vusers_total\x18\a \x01(\x03R\n" +
	"usersTotal\x12!\n" +
	"\fusers_active\x18\b \x01(\x03R\vusersActive\x12\x1f\n" +
	"\vusers_admin\x18\t \x01(\x03R\n" +
	"usersAdmin\x12,\n" +
	"\x12root_jwt_providers\x18\n" +
	" \x01(\x03R\x10rootJwtProviders\x12*\n" +
	"\x11root_auth_enabled\x18\v \x01(\bR\x0frootAuthEnabled\x12*\n" +
	"\x11root_cors_enabled\x18\f \x01(\bR\x0frootCorsEnabled\x123\n" +
	"\amethods\x18\r \x03(\v2\x19.ruto_v1.StatsMethodStatsR\amethods\"X\n" +
	"\x10StatsMethodStats\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x03R\x06active2N\n" +
	"\x05Stats\x12E\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a\x16.ruto_v1.StatsResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/statsB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_stats_proto_rawDescOnce sync.Once
	file_ruto_v1_stats_proto_rawDescData []byte
)

func file_ruto_v1_stats_proto_rawDescGZIP() []byte {
	file_ruto_v1_stats_proto_rawDescOnce.Do(func() {
		file_ruto_v1_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_stats_proto_rawDesc), len(file_ruto_v1_stats_proto_rawDesc)))
	})
	return file_ruto_v1_stats_proto_rawDescData
}

var file_ruto_v1_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ruto_v1_stats_proto_goTypes = []any{
	(*StatsResponse)(nil),    // 0: ruto_v1.StatsResponse
	(*StatsMethodStats)(nil), // 1: ruto_v1.StatsMethodStats
	(*emptypb.Empty)(nil),    // 2: google.protobuf.Empty
}
var file_ruto_v1_stats_proto_depIdxs = []int32{
	1, // 0: ruto_v1.StatsResponse.methods:type_name -> ruto_v1.StatsMethodStats
	2, // 1: ruto_v1.Stats.Get:input_type -> google.protobuf.Empty
	0, // 2: ruto_v1.Stats.Get:output_type -> ruto_v1.StatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ruto_v1_stats_proto_init() }
func file_ruto_v1_stats_proto_init() {
	if File_ruto_v1_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_stats_proto_rawDesc), len(file_ruto_v1_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_stats_proto_goTypes,
		DependencyIndexes: file_ruto_v1_stats_proto_depIdxs,
		MessageInfos:      file_ruto_v1_stats_proto_msgTypes,
	}.Build()
	File_ruto_v1_stats_proto = out.File
	file_ruto_v1_stats_proto_goTypes = nil
	file_ruto_v1_stats_proto_depIdxs = nil
}
