// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: ruto_v1/usr.proto

package ruto_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsrMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrMain) Reset() {
	*x = UsrMain{}
	mi := &file_ruto_v1_usr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrMain) ProtoMessage() {}

func (x *UsrMain) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_usr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrMain.ProtoReflect.Descriptor instead.
func (*UsrMain) Descriptor() ([]byte, []int) {
	return file_ruto_v1_usr_proto_rawDescGZIP(), []int{0}
}

func (x *UsrMain) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UsrMain) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UsrMain) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *UsrMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UsrMain) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsrMain) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UsrGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrGetReq) Reset() {
	*x = UsrGetReq{}
	mi := &file_ruto_v1_usr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrGetReq) ProtoMessage() {}

func (x *UsrGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_usr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrGetReq.ProtoReflect.Descriptor instead.
func (*UsrGetReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_usr_proto_rawDescGZIP(), []int{1}
}

func (x *UsrGetReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UsrListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *ListParamsSt          `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrListReq) Reset() {
	*x = UsrListReq{}
	mi := &file_ruto_v1_usr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrListReq) ProtoMessage() {}

func (x *UsrListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_usr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrListReq.ProtoReflect.Descriptor instead.
func (*UsrListReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_usr_proto_rawDescGZIP(), []int{2}
}

func (x *UsrListReq) GetListParams() *ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *UsrListReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

type UsrListRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaginationInfo *PaginationInfoSt      `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*UsrMain             `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsrListRep) Reset() {
	*x = UsrListRep{}
	mi := &file_ruto_v1_usr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrListRep) ProtoMessage() {}

func (x *UsrListRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_usr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrListRep.ProtoReflect.Descriptor instead.
func (*UsrListRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_usr_proto_rawDescGZIP(), []int{3}
}

func (x *UsrListRep) GetPaginationInfo() *PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *UsrListRep) GetResults() []*UsrMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type UsrCreateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrCreateRep) Reset() {
	*x = UsrCreateRep{}
	mi := &file_ruto_v1_usr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrCreateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrCreateRep) ProtoMessage() {}

func (x *UsrCreateRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_usr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrCreateRep.ProtoReflect.Descriptor instead.
func (*UsrCreateRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_usr_proto_rawDescGZIP(), []int{4}
}

func (x *UsrCreateRep) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UsrLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrLoginReq) Reset() {
	*x = UsrLoginReq{}
	mi := &file_ruto_v1_usr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrLoginReq) ProtoMessage() {}

func (x *UsrLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_usr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrLoginReq.ProtoReflect.Descriptor instead.
func (*UsrLoginReq) Descriptor() ([]byte, []int) {
	return file_ruto_v1_usr_proto_rawDescGZIP(), []int{5}
}

func (x *UsrLoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsrLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UsrLoginRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsrLoginRep) Reset() {
	*x = UsrLoginRep{}
	mi := &file_ruto_v1_usr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsrLoginRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsrLoginRep) ProtoMessage() {}

func (x *UsrLoginRep) ProtoReflect() protoreflect.Message {
	mi := &file_ruto_v1_usr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsrLoginRep.ProtoReflect.Descriptor instead.
func (*UsrLoginRep) Descriptor() ([]byte, []int) {
	return file_ruto_v1_usr_proto_rawDescGZIP(), []int{6}
}

func (x *UsrLoginRep) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

var File_ruto_v1_usr_proto protoreflect.FileDescriptor

const file_ruto_v1_usr_proto_rawDesc = "" +
	"\n" +
	"\x11ruto_v1/usr.proto\x12\aruto_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14ruto_v1/common.proto\"\x98\x01\n" +
	"\aUsrMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\"\x1b\n" +
	"\tUsrGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"r\n" +
	"\n" +
	"UsrListReq\x126\n" +
	"\vlist_params\x18\x01 \x01(\v2\x15.ruto_v1.ListParamsStR\n" +
	"listParams\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01B\v\n" +
	"\t_username\"|\n" +
	"\n" +
	"UsrListRep\x12B\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x19.ruto_v1.PaginationInfoStR\x0epaginationInfo\x12*\n" +
	"\aresults\x18\x02 \x03(\v2\x10.ruto_v1.UsrMainR\aresults\"\x1e\n" +
	"\fUsrCreateRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\vUsrLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x1f\n" +
	"\vUsrLoginRep\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt2\xf6\x03\n" +
	"\x03Usr\x12>\n" +
	"\x04List\x12\x13.ruto_v1.UsrListReq\x1a\x13.ruto_v1.UsrListRep\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/usr\x12>\n" +
	"\x03Get\x12\x12.ruto_v1.UsrGetReq\x1a\x10.ruto_v1.UsrMain\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/usr/{id}\x12B\n" +
	"\x06Create\x12\x10.ruto_v1.UsrMain\x1a\x15.ruto_v1.UsrCreateRep\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/usr\x12H\n" +
	"\x06Update\x12\x10.ruto_v1.UsrMain\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/usr/{id}\x12G\n" +
	"\x06Delete\x12\x12.ruto_v1.UsrGetReq\x1a\x16.google.protobuf.Empty\"\x11\x82\xd3\xe4\x93\x02\v*\t/usr/{id}\x12J\n" +
	"\x05Login\x12\x14.ruto_v1.UsrLoginReq\x1a\x14.ruto_v1.UsrLoginRep\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/usr/login\x12L\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x10.ruto_v1.UsrMain\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/usr/profileB\n" +
	"Z\b/ruto_v1b\x06proto3"

var (
	file_ruto_v1_usr_proto_rawDescOnce sync.Once
	file_ruto_v1_usr_proto_rawDescData []byte
)

func file_ruto_v1_usr_proto_rawDescGZIP() []byte {
	file_ruto_v1_usr_proto_rawDescOnce.Do(func() {
		file_ruto_v1_usr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ruto_v1_usr_proto_rawDesc), len(file_ruto_v1_usr_proto_rawDesc)))
	})
	return file_ruto_v1_usr_proto_rawDescData
}

var file_ruto_v1_usr_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ruto_v1_usr_proto_goTypes = []any{
	(*UsrMain)(nil),          // 0: ruto_v1.UsrMain
	(*UsrGetReq)(nil),        // 1: ruto_v1.UsrGetReq
	(*UsrListReq)(nil),       // 2: ruto_v1.UsrListReq
	(*UsrListRep)(nil),       // 3: ruto_v1.UsrListRep
	(*UsrCreateRep)(nil),     // 4: ruto_v1.UsrCreateRep
	(*UsrLoginReq)(nil),      // 5: ruto_v1.UsrLoginReq
	(*UsrLoginRep)(nil),      // 6: ruto_v1.UsrLoginRep
	(*ListParamsSt)(nil),     // 7: ruto_v1.ListParamsSt
	(*PaginationInfoSt)(nil), // 8: ruto_v1.PaginationInfoSt
	(*emptypb.Empty)(nil),    // 9: google.protobuf.Empty
}
var file_ruto_v1_usr_proto_depIdxs = []int32{
	7,  // 0: ruto_v1.UsrListReq.list_params:type_name -> ruto_v1.ListParamsSt
	8,  // 1: ruto_v1.UsrListRep.pagination_info:type_name -> ruto_v1.PaginationInfoSt
	0,  // 2: ruto_v1.UsrListRep.results:type_name -> ruto_v1.UsrMain
	2,  // 3: ruto_v1.Usr.List:input_type -> ruto_v1.UsrListReq
	1,  // 4: ruto_v1.Usr.Get:input_type -> ruto_v1.UsrGetReq
	0,  // 5: ruto_v1.Usr.Create:input_type -> ruto_v1.UsrMain
	0,  // 6: ruto_v1.Usr.Update:input_type -> ruto_v1.UsrMain
	1,  // 7: ruto_v1.Usr.Delete:input_type -> ruto_v1.UsrGetReq
	5,  // 8: ruto_v1.Usr.Login:input_type -> ruto_v1.UsrLoginReq
	9,  // 9: ruto_v1.Usr.GetProfile:input_type -> google.protobuf.Empty
	3,  // 10: ruto_v1.Usr.List:output_type -> ruto_v1.UsrListRep
	0,  // 11: ruto_v1.Usr.Get:output_type -> ruto_v1.UsrMain
	4,  // 12: ruto_v1.Usr.Create:output_type -> ruto_v1.UsrCreateRep
	9,  // 13: ruto_v1.Usr.Update:output_type -> google.protobuf.Empty
	9,  // 14: ruto_v1.Usr.Delete:output_type -> google.protobuf.Empty
	6,  // 15: ruto_v1.Usr.Login:output_type -> ruto_v1.UsrLoginRep
	0,  // 16: ruto_v1.Usr.GetProfile:output_type -> ruto_v1.UsrMain
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ruto_v1_usr_proto_init() }
func file_ruto_v1_usr_proto_init() {
	if File_ruto_v1_usr_proto != nil {
		return
	}
	file_ruto_v1_common_proto_init()
	file_ruto_v1_usr_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ruto_v1_usr_proto_rawDesc), len(file_ruto_v1_usr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ruto_v1_usr_proto_goTypes,
		DependencyIndexes: file_ruto_v1_usr_proto_depIdxs,
		MessageInfos:      file_ruto_v1_usr_proto_msgTypes,
	}.Build()
	File_ruto_v1_usr_proto = out.File
	file_ruto_v1_usr_proto_goTypes = nil
	file_ruto_v1_usr_proto_depIdxs = nil
}
