// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: ruto_v1/usr.proto

package ruto_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Usr_List_FullMethodName       = "/ruto_v1.Usr/List"
	Usr_Get_FullMethodName        = "/ruto_v1.Usr/Get"
	Usr_Create_FullMethodName     = "/ruto_v1.Usr/Create"
	Usr_Update_FullMethodName     = "/ruto_v1.Usr/Update"
	Usr_Delete_FullMethodName     = "/ruto_v1.Usr/Delete"
	Usr_Login_FullMethodName      = "/ruto_v1.Usr/Login"
	Usr_GetProfile_FullMethodName = "/ruto_v1.Usr/GetProfile"
)

// UsrClient is the client API for Usr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsrClient interface {
	List(ctx context.Context, in *UsrListReq, opts ...grpc.CallOption) (*UsrListRep, error)
	Get(ctx context.Context, in *UsrGetReq, opts ...grpc.CallOption) (*UsrMain, error)
	Create(ctx context.Context, in *UsrMain, opts ...grpc.CallOption) (*UsrCreateRep, error)
	Update(ctx context.Context, in *UsrMain, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *UsrGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Login(ctx context.Context, in *UsrLoginReq, opts ...grpc.CallOption) (*UsrLoginRep, error)
	GetProfile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsrMain, error)
}

type usrClient struct {
	cc grpc.ClientConnInterface
}

func NewUsrClient(cc grpc.ClientConnInterface) UsrClient {
	return &usrClient{cc}
}

func (c *usrClient) List(ctx context.Context, in *UsrListReq, opts ...grpc.CallOption) (*UsrListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsrListRep)
	err := c.cc.Invoke(ctx, Usr_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrClient) Get(ctx context.Context, in *UsrGetReq, opts ...grpc.CallOption) (*UsrMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsrMain)
	err := c.cc.Invoke(ctx, Usr_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrClient) Create(ctx context.Context, in *UsrMain, opts ...grpc.CallOption) (*UsrCreateRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsrCreateRep)
	err := c.cc.Invoke(ctx, Usr_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrClient) Update(ctx context.Context, in *UsrMain, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Usr_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrClient) Delete(ctx context.Context, in *UsrGetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Usr_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrClient) Login(ctx context.Context, in *UsrLoginReq, opts ...grpc.CallOption) (*UsrLoginRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsrLoginRep)
	err := c.cc.Invoke(ctx, Usr_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrClient) GetProfile(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UsrMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsrMain)
	err := c.cc.Invoke(ctx, Usr_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsrServer is the server API for Usr service.
// All implementations must embed UnimplementedUsrServer
// for forward compatibility.
type UsrServer interface {
	List(context.Context, *UsrListReq) (*UsrListRep, error)
	Get(context.Context, *UsrGetReq) (*UsrMain, error)
	Create(context.Context, *UsrMain) (*UsrCreateRep, error)
	Update(context.Context, *UsrMain) (*emptypb.Empty, error)
	Delete(context.Context, *UsrGetReq) (*emptypb.Empty, error)
	Login(context.Context, *UsrLoginReq) (*UsrLoginRep, error)
	GetProfile(context.Context, *emptypb.Empty) (*UsrMain, error)
	mustEmbedUnimplementedUsrServer()
}

// UnimplementedUsrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsrServer struct{}

func (UnimplementedUsrServer) List(context.Context, *UsrListReq) (*UsrListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedUsrServer) Get(context.Context, *UsrGetReq) (*UsrMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUsrServer) Create(context.Context, *UsrMain) (*UsrCreateRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUsrServer) Update(context.Context, *UsrMain) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUsrServer) Delete(context.Context, *UsrGetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUsrServer) Login(context.Context, *UsrLoginReq) (*UsrLoginRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUsrServer) GetProfile(context.Context, *emptypb.Empty) (*UsrMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedUsrServer) mustEmbedUnimplementedUsrServer() {}
func (UnimplementedUsrServer) testEmbeddedByValue()             {}

// UnsafeUsrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsrServer will
// result in compilation errors.
type UnsafeUsrServer interface {
	mustEmbedUnimplementedUsrServer()
}

func RegisterUsrServer(s grpc.ServiceRegistrar, srv UsrServer) {
	// If the following call pancis, it indicates UnimplementedUsrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Usr_ServiceDesc, srv)
}

func _Usr_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsrListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usr_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrServer).List(ctx, req.(*UsrListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usr_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsrGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usr_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrServer).Get(ctx, req.(*UsrGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usr_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsrMain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usr_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrServer).Create(ctx, req.(*UsrMain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usr_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsrMain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usr_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrServer).Update(ctx, req.(*UsrMain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usr_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsrGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usr_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrServer).Delete(ctx, req.(*UsrGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usr_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsrLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usr_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrServer).Login(ctx, req.(*UsrLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usr_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usr_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrServer).GetProfile(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Usr_ServiceDesc is the grpc.ServiceDesc for Usr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ruto_v1.Usr",
	HandlerType: (*UsrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Usr_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Usr_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Usr_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Usr_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Usr_Delete_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Usr_Login_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Usr_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ruto_v1/usr.proto",
}
