name: Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - run: go test ./...

  build:
    name: Build and deploy ${{ matrix.service }}
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: core
            image: ruto-core:latest
            dockerfile: docker/core.Dockerfile
          - service: gateway
            image: ruto-gateway:latest
            dockerfile: docker/gateway.Dockerfile
    env:
      OWNER: ${{ github.repository_owner }}
      IMAGE: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v6

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker build -f ${{ matrix.dockerfile }} -t ghcr.io/$OWNER/$IMAGE .

      - run: docker push ghcr.io/$OWNER/$IMAGE
