name: Deploy
on:
  push:
    branches:
      - master
      - develop
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - run: go mod download

      - run: go test ./...

  build:
    name: Build and deploy ${{ matrix.service }}
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: core
            image: ruto-core
            dockerfile: docker/Dockerfile.core
          - service: gateway
            image: ruto-gateway
            dockerfile: docker/Dockerfile.gateway
    env:
      OWNER: ${{ github.repository_owner }}
      IMAGE: ${{ matrix.image }}
      TAG: ${{ github.ref_name == 'develop' && 'develop' || 'latest' }}
    steps:
      - uses: actions/checkout@v6

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker build -f ${{ matrix.dockerfile }} -t ghcr.io/$OWNER/$IMAGE:$TAG .

      - run: docker push ghcr.io/$OWNER/$IMAGE:$TAG
