name: Deploy
on:
  push:
    branches:
      - disabled
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      OWNER: rendau
      IMAGE: ruto:latest
    steps:
      - uses: actions/checkout@v6

      - run: go mod download

      # - run: go test -v ./...

      - run: make

      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $ --password-stdin

      - run: docker build -t ghcr.io/$OWNER/$IMAGE .

      - run: docker push ghcr.io/$OWNER/$IMAGE
